### ISSUE TITLE
这个项目是否在实际生产环境已使用

### ISSUE THREAD

**Issue by junjiem** [InterestingLab/waterdrop#109]
我看了下项目文档，这个只是基于spark的单流程的数据采集、聚合和传输的系统，无法满足实际应用中实时流计算的要求。

**Comment by garyelephant** [comment]
你好，感谢你关注这个项目，请教你说的实际应用中的实时流计算具体指什么场景和功能需求？我们考虑在下个版本中丰富一下。

**Comment by junjiem** [comment]
真实的实时流计算是需要用到实时数据和存量数据进行关联组合，有时还需要开启时间窗口等混合使用才能完成一个实时流业务。

**Comment by garyelephant** [comment]
你说的很有道理，我们在实际应用中，还用到了stream-stream join。相关功能我们在之后的迭代版本中都会加上。
