### ISSUE TITLE
是否可以提供一个简单的架构图,并做一些简单介绍说明

### ISSUE THREAD

**Issue by ryan-bin** [InterestingLab/waterdrop#110]
类似于：
https://github.com/Tencent/angel/blob/master/docs/overview/code_framework.md

**Comment by garyelephant** [comment]
@ryan-bin  @感谢你关注这个项目，我们 将于@RickyHuo 近期提供技术架构图，请多提建议.

**Comment by liuxinsi** [comment]
同求，可以更直观的了解下。

**Comment by RickyHuo** [comment]
我们在Elastic Meetup上项目介绍PPT https://elasticsearch.cn/slides/127#page=14  @ryan-bin @liuxinsi
