### ISSUE TITLE
Guardian TODO

### ISSUE THREAD

**Issue by garyelephant** [InterestingLab/waterdrop#116]
guardian: 

1. 监控对应的api使用文档有点简陋，缺乏每个API的参数详情，如新增监控app的配置的时候，body里面每个配置什么意思，具体返回值什么意思。

2. 监控文档里面需要加上config.json的其他参数的解释，比如alertmanager相关的，介绍一下webhook，email的用法和参数。

3. email方式发送的报警邮件的标题和内容需要重新定义一下，现在收到邮件从内容上看有点搞不清楚发生了什么。

4. webhook方式的报警，对应的webhook api怎么实现才能收到webhook发给他的报警内容，在文档里说明一下。

5. 【可不做】使用了apscheduler后，监控代码中如果抛出异常，会被吞噬掉，不会抛出来，对于排查问题有点麻烦，这个看能不能把异常抛出来。

**Comment by garyelephant** [comment]
6. guardian 集成的发布版本中
7. waterdrop启动时，可配置自动加入到guardian监控中。

**Comment by RickyHuo** [comment]
- [ ] 1
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
