### ISSUE TITLE
同一批数据的多种处理流程

### ISSUE THREAD

**Issue by qaz163wsx** [InterestingLab/waterdrop#118]
针对同批数据，如要执行10+次sql统计，每个统计结果输出至kafka不同topic中。
请问该如何进行配置可以达到优化？尽可能使用到spark cache机制，谢谢

**Comment by garyelephant** [comment]
你好，目前支持相同处理流程(即filter)吐出的数据,输出到不同的output中；还不支持不同的处理流程，即不同的pipeline，如果需要可配置多个waterdrop 配置文件实现。多pipeline功能将会在2个月内加入，如果有兴趣可为waterdrop贡献代码。

**Comment by qaz163wsx** [comment]
ok,我会持续关注

**Comment by garyelephant** [comment]
@qaz163wsx 您好，Waterdrop 近期会有重大更新，将在新版中支持“多pipeline”功能。现在我们先提供一个`支持多pipeline功能`的预发beta版本，用于大家做功能调研和验证，
`“多pipeline”功能`的介绍如下：

Waterdrop 支持在一个实例中，以多Pipeline的方式来处理数据，即允许每个pipeline以自己的方式来处理数据，并输出。并且在同一个waterdrop实例中，各个pipeline对数据的处理能够做到互不影响。 

可执行软件包下载地址如下：https://pan.baidu.com/s/1lrJOcb6aUEf_39ZB8tUXQw

详细的文档，请见下载地址中的包含的：《Waterdrop中多pipeline功能的使用文档》

想了解 Waterdrop 其他的信息，详见官方文档：
https://interestinglab.github.io/waterdrop/
