### ISSUE TITLE
和kafaka kafka_2.11-0.11.0.1兼容吗

### ISSUE THREAD

**Issue by pxh520** [InterestingLab/waterdrop#130]
执行时报
Exception in thread "main" java.lang.ClassCastException: kafka.cluster.BrokerEndPoint cannot be cast to kafka.cluster.Broker
我的kafka版本时0.11

**Comment by garyelephant** [comment]
请 @RickyHuo 解决一下

**Comment by pxh520** [comment]
kafka换了0.8也报同样错误

**Comment by RickyHuo** [comment]
@pxh520  我自己搭建了kafka_2.11-0.11.0.1的单点服务，启动waterdrop消费数据，整个过程没有异常。

**Comment by garyelephant** [comment]
已经与 @pxh520 一起排查，是 @pxh520 本地的多个jar依赖冲突导致的，waterdrop无异常，close issue
