### ISSUE TITLE
KafkaStream消费topic的消息体是一个序列化javabean实体，如何修改input

### ISSUE THREAD

**Issue by liujianrong** [InterestingLab/waterdrop#154]
请问一下如何重写input插件，可以用自定义的实体和反序列化工具类么？
val messageHandler = (mmd: MessageAndMetadata[String, String]) => (mmd.topic, mmd.message())

    val topics = config.getString("topics").split(",").toSet
    km = new KafkaManager(kafkaParams)
    val fromOffsets =
    km.setOrUpdateOffsets(topics, consumerConfig.getString("group.id"))

    val inputDStream = KafkaUtils.createDirectStream[String, String, StringDecoder, StringDecoder, (String, String)](
      ssc,
      kafkaParams,
      fromOffsets,
      messageHandler)

    inputDStream.transform { rdd =>
      offsetRanges = rdd.asInstanceOf[HasOffsetRanges].offsetRanges
      rdd
    }

**Comment by RickyHuo** [comment]
https://github.com/InterestingLab/waterdrop-example

可以根据这个项目继承我们提供的API重写一个你自己的KafkaInput集成到Waterdrop中就可以了，只要最后返回的结果是DStream[(String, String)]。可以根据你的需求自定义你的实体和反序列化工具类。

**Comment by liujianrong** [comment]
ok，thanks
