### ISSUE TITLE
请问在导入执行过程中执行失败重试的情况下如何保证数据不重复

### ISSUE THREAD

**Issue by liyuance** [InterestingLab/waterdrop#198]
RT

**Comment by garyelephant** [comment]
@liyuance 你好。你的使用场景是什么呢？input，output都是什么？

最好是output支持幂等，重试时，即可不重复。如果做不幂等，想不重复是很难的。如果总是失败，可以尝试，把数据从业务上分成多份，每次只导一部分。

**Comment by liyuance** [comment]
计划用这个工具从hive里面往clickhouse里面导入数据，想了解当导入任务运行过程中部分任务失败重试的话能保证数据往clickhouse里面写的数据不重复吗？谢谢

**Comment by RickyHuo** [comment]
@liyuance waterdrop写ClickHouse的代码部分目前不支持幂等。导入失败重新导入的话，可能需要将表里之前导入成功给的数据删除。
