### ISSUE TITLE
hive到clickhouse table not found

### ISSUE THREAD

**Issue by panda403** [InterestingLab/waterdrop#202]
导入hive中的数据到clickhouse的时候，出现table not found，waterdrop-env.sh 配置如下：
SPARK_HOME=/waterdrop/spark-2.4.0-bin-hadoop2.7
JAVA_HOME=/waterdrop/java8
HADOOP_HOME=/etc/hadoop/

已将hive-site.xml配置文件拷贝到/etc/hadoop/conf中

**Comment by RickyHuo** [comment]
@panda403 加我微信chodomatte1994 帮你排查一下
