### ISSUE TITLE
请问waterDrop的实现原理

### ISSUE THREAD

**Issue by xu0612204126** [InterestingLab/waterdrop#220]
因为我看到“自定义FIlter插件”的process方法的入参是DataSet，所以猜想咱们应该是将 数据流转换成了 tempView，然后创建的DataSet，之后调用FIlter插件做数据转换的。 

但是我有一个应用场景是：
  从kafka的多个topic中获取数据，每种topic的分区数可能不同，里面的数据结构也不同，这种情况下，我们还能使用自定义插件来实现吗？ 如果可以，给个思路。

**Comment by garyelephant** [comment]
如果你是在一个waterdrop实例里面，读取多个topic，当前release版本是不支持的，我们近期会上线一个多pipeline功能，允许不同的topic生成不同的dataset，你实现的插件，只要处理特定的dataset即可。

**Comment by thinkinerp** [comment]
请问，多pipeline功能大概什么时候上线
