### ISSUE TITLE
咨询同步性能

### ISSUE THREAD

**Issue by nickevin** [InterestingLab/waterdrop#234]
我们现有一张表有 4 亿行，200 个字段，平均一条记录有 16 KB，如果使用 waterdrop 来同步，预估需要耗时多久？

**Comment by garyelephant** [comment]
您好，感谢使用waterdrop，需要跟您确认几个问题：
1, 你的表存在哪里，是不是分布式集群，资源规模有多大？
2. 数据要同步到哪里，是不是分布式集群，资源规模有多大？

另，可加微信`garyelephant`，我们即时沟通，了解需求。

**Comment by nickevin** [comment]
1：源表在 hive，有 4 亿行，200 个字段，分布式部署
2：目标表在 clickhouse，单机部署，16 核心，32 GB

由于 hive 是关联方负责，不知道我提供的信息是否充足，如果缺少的话，我再去确认下。

谢谢。

**Comment by haitaodd** [comment]
> 1：源表在 hive，有 4 亿行，200 个字段，分布式部署
> 2：目标表在 clickhouse，单机部署，16 核心，32 GB，SSD 500 G
> 
> 由于 hive 是关联方负责，不知道我提供的信息是否充足，如果缺少的话，我再去确认下。
> 
> 谢谢。

如果单纯的同步表，可以考虑用专业的ETL工具，比如[apache nifi](https://nifi.apache.org/)，速度的话，与
1）hive原始文件格式（比如外部表，存储为json？orc？parquet etc.）
2）目标端jdbc配置
3）网络io
等有关
