### ISSUE TITLE
【已解决】waterdrop-1.2.1 启动报错，提示 ‘/opt/waterdrop-1.2.1/lib’: 没有那个文件或目录

### ISSUE THREAD

**Issue by xu0612204126** [InterestingLab/waterdrop#240]
发现下载的waterdrop-1.2.1 .zip解压后确实没有lib文件，但是start-waterdrop.sh却引用了lib文件。

**Comment by garyelephant** [comment]
你好，你下载的是源代码，不是可执行软件包。Waterdrop 为你提供了现成的可直接执行的软件包，
请参考此文档下载：

https://interestinglab.github.io/waterdrop/#/zh-cn/installation

**Comment by garyelephant** [comment]
有其他需求，请加微信`garyelephant`为你解答。
