### ISSUE TITLE
when input is hive,output is mongodb,how to set  the  data can update by a column 

### ISSUE THREAD

**Issue by celestewang1026** [InterestingLab/waterdrop#242]
I used waterdrop ,the input is hive,the output is mongodb,
1.how I set a bussiness key ,like user_id mapping the mongo primary_key=_id.
2.how I set can make the data that to mongdb is update ,not insert by primary_key

**Comment by xu0612204126** [comment]
我猜测，需要自定义一个input 和outPut吧

**Comment by garyelephant** [comment]
@kid-xiong 解答一下

**Comment by kid-xiong** [comment]
1.如果你想将业务唯一key变成_id，直接在sql里写就行了，例如 select user_id as _id ....;如果你的唯一key是多个字段组成,select concat(field_1,'-',field_2.....) as _id
2.在你的mongoDBOutput增加一个参数:writeconfig.replaceDocument =  "false"；就可以起到update的效果了
有什么不明白的可以+我微信 374545700

**Comment by celestewang1026** [comment]
> 1.如果你想将业务唯一key变成_id，直接在sql里写就行了，例如 select user_id as _id ....;如果你的唯一key是多个字段组成,select concat(field_1,'-',field_2.....) as _id
> 2.在你的mongoDBOutput增加一个参数:writeconfig.replaceDocument = "false"；就可以起到update的效果了
> 有什么不明白的可以+我微信 374545700

get it! Thks,but for where I can get all params like "writeconfig.replaceDocument"
