### ISSUE TITLE
MultiPipeLine的问题

### ISSUE THREAD

**Issue by xu0612204126** [InterestingLab/waterdrop#243]
**操作描述:**
1.我参照《Waterdrop中多pipeline功能的使用文档.pdf》配置了一个源多个输出的文件，格式如下：
![image](https://user-images.githubusercontent.com/8637414/53627684-11778900-3c44-11e9-910e-133998c23f7c.png)

2.启动waterDrop，报错
![image](https://user-images.githubusercontent.com/8637414/53627731-2d7b2a80-3c44-11e9-90ba-3404f382afdf.png)

**我的问题：**
1.请问，上述问题怎么解决
2.别人提出的，https://github.com/InterestingLab/waterdrop/issues/153这问题目前版本已经解决了吗？ 怎么使用？
3.多PipeLine的任务，源代码中是怎么实现的，需要参照哪一部分。

**Comment by garyelephant** [comment]
你好，
（1）你可能使用的是不支持多pipeline的waterdrop版本
（2）之前的文档《Waterdrop中多pipeline功能的使用文档-v2.pdf》关于pipeline名称的配置方式有误，现已修正。


请从这里，重新下载waterdrop可执行包(只有从这里下载的预发版本支持多pipeline)，和文档
《Waterdrop中多pipeline功能的使用文档-v2.pdf》

https://pan.baidu.com/s/1lrJOcb6aUEf_39ZB8tUXQw
