### ISSUE TITLE
导入elasticsearch数据时怎么设置更新参数

### ISSUE THREAD

**Issue by zjybeijing** [InterestingLab/waterdrop#246]
默认都是追加的，怎么指定更新字段

**Comment by RickyHuo** [comment]
@zjybeijing 
```
elasticsearch {
      hosts = ["localhost:9200"]
      index = "waterdrop-${now}"
      es.batch.size.entries = 100000
      es.mapping.id = "pid"
      es.write.operation = "upsert"
      index_time_format = "yyyy.MM.dd"
  }
```

详情请参考
> [waterdrop配置文件](https://interestinglab.github.io/waterdrop/#/zh-cn/configuration/output-plugins/Elasticsearch)
> [Elasticsearch Configuration](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/configuration.html#cfg-mapping)

**Comment by FishermanZzhang** [comment]
```
{
  "settings": {
    "number_of_shards": 5,
    "number_of_replicas": 1
  },
  "mappings": {
      "title":{
        "type":"text",
        "analyzer":"ik_max_word",
        "search_analyzer":"ik_smart"
      }
  }
}
```
如何在导入的时候指定 `number_of_shards` 、`analyzer` 等信息

**Comment by RickyHuo** [comment]
> ```
> {
>   "settings": {
>     "number_of_shards": 5,
>     "number_of_replicas": 1
>   },
>   "mappings": {
>       "title":{
>         "type":"text",
>         "analyzer":"ik_max_word",
>         "search_analyzer":"ik_smart"
>       }
>   }
> }
> ```
> 
> 如何在导入的时候指定 `number_of_shards` 、`analyzer` 等信息

分片个数和分词器在配置index template时指定，与写入无关
