### ISSUE TITLE
Structured Streaming Implementation

### ISSUE THREAD

**Issue by garyelephant** [InterestingLab/waterdrop#256]
### 需要改

1. ** Structured Streaming 不支持 JSON 数据处理？**

2. CommandLineUtils.scala中engine命令缩写需要改。

3. WaterMaker Filter 英文写错了

### 讨论

1. 我们每实现一个streaming input，都要实现一个对应的spark streaming 和structured streaming input

2. 我们每实现一个output, 都要实现一个对应的structured streaming 和 batch output

3. 用户所需要的structured streaming的input(kafka), output(kafka) 实现了吗？

4. 哪些filter可以用于structured streaming ？

5. 文档需要补充的：
（1）[优先] Plugin:  Watermark Filter, Kafka Input, Kafka Output
（2）[优先] structured streaming engine的start-waterdrop.sh 启动方式
（3）[优先] 插件文档中需要标示出每种插件可用的engine
（4）[优先] Window功能使用文档
（4）Engine介绍文档：spark streaming，structured streaming, flink, batch(要不要成为一种engine)，engine指的是streaming的engine，还是普遍意义上的engine
（5）如何开发structured streaming插件
（6）Plugin: Deduplication,

6. 本次升级是否是破坏性升级？---> 必须指定engine ？

7. Join Filter 是干嘛的？

8. spark streaming 和structured streaming的不同engine的插件的用户参数是否一样：
（1）[优先] Kafka Input/Output  
（2）[优先] Stdout Output
（3）Mongo Output 

9. input.batch ? output.batch ? 

10. 几个structured streaming相关的常见问题：
（1）Trigger是干什么的，waterdrop上怎么使用？
（2）event time怎么用
（3）checkpoint怎么用 【需要验证：structured 是否支持多个output，是否每个output都有自己的checkpoint】
（4）window怎么用？【需要验证：功能】
（5）stream static join怎么用？
（6）哪些filter不能在structured streaming上面使用？

11. structured streaming 监控的实现有什么想法？

**Comment by garyelephant** [comment]
下一步计划：

(1) 发布预发版，先不merge到master

**Comment by RickyHuo** [comment]
* [ ] 验证Kafka Output 可用，并且统一不同engine kafka output的配置方式，即文档。
* [ ] 梳理所有Filter可以用于哪些engine
* [ ]  engine 改为必填参数，`streaming` engine 改为`sparkstreaming`
* [ ] 需要验证：structured 是否支持多个output，是否每个output都有自己的checkpoint
* [ ] 需要验证window怎么用，并补充文档。
* [ ]  Stdout Output 需要统一不同engine kafka output的配置方式，即文档。
* [ ] 文档需要补充的, 标记为 [优先]的

**Comment by garyelephant** [comment]
@RickyHuo 👍

**Comment by RickyHuo** [comment]
[Use Case Discovery :: Apache Spark Structured Streaming with Multiple-sinks (2 for now).](https://www.linkedin.com/pulse/use-case-discovery-apache-spark-structured-streaming-2-weichberger)

**Comment by RickyHuo** [comment]
```
sql {
    table_name = "ref"
    sql = "select name, count(name) as count, window, date_format(window.end, 'MMM-dd HH:mm') as time from ref group by window(dt, '10 minutes', '5 minutes'), name"
  }
```
