### ISSUE TITLE
WaterDrop配置Kafka为Input，Stout为输出，但是却收集不到kafka的数据，为什么？

### ISSUE THREAD

**Issue by xu0612204126** [InterestingLab/waterdrop#258]
**环境说明：**
kafka的版本是： kafka_2.11-2.1.0，WaterDrop版本是1.2.1
**application.conf配置说明：**
spark {
  # Waterdrop defined streaming batch duration in seconds
  spark.streaming.batchDuration = 5

  spark.app.name = "Waterdrop"
  spark.ui.port = 13000
}

input {
  kafkaStream {
    topics = "waterDemo"
    consumer.auto.offset.reset="earliest"
    #consumer.bootstrap.servers = "192.168.10.212:9098"
    consumer.bootstrap.servers = "192.168.10.211:9099,192.168.10.212:9099,192.168.10.213:9099"
    consumer.group.id = "waterdrop_group"
  }
}

filter{
}

output {
  stdout{
  }
  elasticsearch {
    hosts = ["192.168.10.216:9200"]
    index = "waterdrop-${now}"
    es.batch.size.entries = 100000
    index_time_format = "yyyy.MM.dd"
  }
}
**kafka生产端的代码：**

public class NormalKafkaProducter {

    //public static final String TOPIC = "D_GJ_SJWBSWLSB";
    public static final String TOPIC = "waterDemo";
    public static void main(String[] args) throws SQLException {
        Logger logger = LoggerFactory.getLogger(NormalKafkaProducter.class);

        Properties props = new Properties();
        props.put("bootstrap.servers", "192.168.10.211:9099,192.168.10.212:9099,192.168.10.213:9099");
        props.put("key.serializer", "org.apache.kafka.common.serialization.StringSerializer");
        props.put("value.serializer", "org.apache.kafka.common.serialization.StringSerializer");

        KafkaProducer<String, String> producer = new KafkaProducer<String,String>(props);

      
        String selectSql="select * from (SELECT SYSTEMID ,GJHM , GJMC ,HMLX,HDFSDD,ROWNUM R  FROM D_GJ_STLGGJB  order  by ZYK_GXSJ  ) where R<1500   ";
            Connection conn=null;
            PreparedStatement pstm=null;
            ResultSet resultSet=null;
            int i=0;
            try {
                conn=  DBUtil.getConnection();
                //  conn.setAutoCommit(false);//1,首先把Auto commit设置为false,不让它自动提交
                pstm=  conn.prepareStatement(selectSql);
                resultSet=pstm.executeQuery();

                while(resultSet.next() ){
                    String kafkaData=StringUtils.trimToEmpty(resultSet.getString("SYSTEMID"))+","+StringUtils.trimToEmpty(resultSet.getString("GJHM"));
                    ProducerRecord<String, String> record = new ProducerRecord<String,String>(TOPIC,"" ,  kafkaData);
                    producer.send(record);
                    System.out.println(">>>>>>>>>>>>>>>>>>>>>"+i);
                    i++;
                    if(i%100==0){
                        Thread.sleep(1000);
                    }
                }
                producer.close();

            } catch (Exception e) {
                e.printStackTrace();
            }finally {
                pstm.close();
                DBUtil.closeConnection();
            }

        }

    }
**测试结果：**
控制台上没有任何输出。

此问题，困扰了很久，希望能尽快帮忙解决下。

**Comment by garyelephant** [comment]
感谢反馈，我们为你排查一下

**Comment by xu0612204126** [comment]
你好，这问题已经解决了。
把ZK重新清理了下，就可以了。

**Comment by garyelephant** [comment]
@xu0612204126 真棒👍
