### ISSUE TITLE
ClickHouse Output Plugin Supports Type Of  Nullable(T)

### ISSUE THREAD

**Issue by malei92119** [InterestingLab/waterdrop#277]
spark 本地测试导入 报错
Plugin[io.github.interestinglab.waterdrop.output.Clickhouse] contains invalid config, error: clickHouse data type [(Nullable(Float64),false)], [(Nullable(Float64),false)], [(Nullable(Float64),false)], [(Nullable(Int32),false)], [(Nullable(Int32),false)], [(Nullable(Int32),false)] not support in current version.

hive表：
![图片](https://user-images.githubusercontent.com/19967453/54903085-039ce700-4f16-11e9-90b5-903cdbfb31ca.png)

.conf 配置
![图片](https://user-images.githubusercontent.com/19967453/54903139-27f8c380-4f16-11e9-8a8b-d9a477bd2120.png)

帮忙看下是哪里的问题，第一次使用这个;
![图片](https://user-images.githubusercontent.com/19967453/54903180-3e068400-4f16-11e9-878e-cb293d3d4c79.png)
在filter中加入转换，还是不对

**Comment by malei92119** [comment]
![图片](https://user-images.githubusercontent.com/19967453/54903263-7908b780-4f16-11e9-8225-f0aeb86a7170.png)
ck表接口如图所示

**Comment by RickyHuo** [comment]
https://github.com/yandex/clickhouse-jdbc/blob/master/src/test/java/ru/yandex/clickhouse/integration/ClickHousePreparedStatementTest.java#L207

**Comment by RickyHuo** [comment]
#294
