### ISSUE TITLE
filterConfObj.foreach遍历顺序不可控

### ISSUE THREAD

**Issue by RickyHuo** [InterestingLab/waterdrop#29]
filterConfObj.foreach遍历顺序不是按照配置文件中插件顺序从上至下遍历

**Comment by garyelephant** [comment]
方案一：
由于typesafe 的config在加载配置时，未能保留配置的顺序，所以我们只能修改application.conf 中的配置格式从kv的map形式，改为list形式；
```
# 更改后的配置类似
filter {
	{
		type = split
		...
	}
	{
		type = grok
		...
	}
}
```
另外如果这样修改，如何支持条件判断相关的配置如：if else，考虑通过如下方式支持：
```
# 更改后的配置类似，通过如下配置实现一个 if else 逻辑:
filter {
	{
		condition = "status >= 400"
		type = split
		...
	}
	{
	    condition = "status < 400"
		type = grok
		...
	}
}
```

整体感觉，这种配置让人理解起来不够直观和简单，但是实现相对容易。


方案二：寻找其他配置解析库的替代方案，目前只找到了这一个，是否满足需求，还在确认中：
http://www.cfg4j.org/

方案三：使用antlr4自定义一套配置文件解析规则，同时满足配置看起来直观、简单的需求和支持条件判断(if else)的需求

**Comment by garyelephant** [comment]
还有1种方案是修改typesafe config的源码，把它存储配置的数据结构改成LinkedHashMap，就能保持顺序。

注意：这样还是不满足`能够做条件判断`的需求。

**Comment by garyelephant** [comment]
配置文件parser需求：

* kv形式

* plugin保持顺序

* 有条件判断

* Field引用

* 环境变量／自定义变量的在配置中替换(自定义变量的引用方式)

* 全局配置

**Comment by garyelephant** [comment]
antlr4 grammer file见：

配置文件示例见：

经antlr4解析后，生成如下AST树：

![image](https://user-images.githubusercontent.com/2291859/30246978-40a0a3f2-963b-11e7-9846-1aaab359500a.png)

根据此AST树和antlr4自动生成的代码进行listener/vistor遍历即可实现配置文件解析功能，解析后的配置转换为typesafe config,供各个插件使用。

需求满足情况如下：

* 【支持】kv形式

* 【支持】plugin保持顺序

* 【支持】有条件判断

* 【支持】Field引用

* 【支持但未实现】环境变量／自定义变量的在配置中替换(自定义变量的引用方式)

* 【支持但未实现】全局配置

* 【需调研】配置文件错误提示和定位

**Comment by garyelephant** [comment]
@RickyHuo
