### ISSUE TITLE
add elasticsearch7 support ?

### ISSUE THREAD

**Issue by zihjiang** [InterestingLab/waterdrop#330]
请问有打算支持elasticsearch7么?

**Comment by garyelephant** [comment]
你好，如果想使用 elasticsearch7可以你可以开发自己的插件，如果需要我们来支持的话，预期排期大约是2019年9月1日之前支持。请加微信`garyelephant`，我们来跟进你的需求。

**Comment by zihjiang** [comment]
我把源代码重新编译了一下, 依赖改成了7.1.1, 就可以支持7
