### ISSUE TITLE
共两个问题，问题1：deploy-mode并不是必须的

### ISSUE THREAD

**Issue by Tasselmi** [InterestingLab/waterdrop#333]
提交运行命令如下：

`bin/start-waterdrop.sh --master yarn-client --config ./config/kafkaStream.conf`
结果报错：Error: Missing option --deploy-mode

但是其实真相是：--master选项里面有yarn-client或者yarn-cluster，这样其实--deploy-mode是或选的，并不是必选的。

**Comment by garyelephant** [comment]
--master yarn --deploy-mode client
