### ISSUE TITLE
共两个问题，问题2：HA spark怎么配置spark-home

### ISSUE THREAD

**Issue by Tasselmi** [InterestingLab/waterdrop#334]
如题，我配置的spark-home如下：
`SPARK_HOME=/opt/modules/spark-2.4.3-bin-hadoop2.6`

然后我有个问题想问啊，因为本身spark我通过zookeeper进行了HA配置，那么，SPARK_HOME这个master其实随时有可能挂掉的，不知道，这种情况，开发方可否想过~

**Comment by garyelephant** [comment]
你好，抱歉，没有理解你说的意思，请加微信`garyelephant`与你进一步沟通需求
