### ISSUE TITLE
请问怎么让start-waterdrop在后台运行

### ISSUE THREAD

**Issue by Tasselmi** [InterestingLab/waterdrop#335]
如题，试了 --daemon 和 -daemon 好像都没作用~~

**Comment by garyelephant** [comment]
你好，你指定的master 参数和deploy-mode 是哪个

**Comment by Tasselmi** [comment]
--master yarn
--deploy-mode cluster或client

我的理解是dropwater本身自己是一个服务，应该可以后台运行的呀~ 不知道和这几个参数有啥关系呢

**Comment by garyelephant** [comment]
可以后台运行，但是默认日志会从标准输出打印出来，可以做一下重定向。
