### ISSUE TITLE
ClassNotFoundException: org.apache.spark.sql.sources.v2.StreamWriteSupport

### ISSUE THREAD

**Issue by RickyHuo** [InterestingLab/waterdrop#347]
Waterdrop Version: 1.3.8

Spark Version: 2.2.0

config: 

```
input {

  jdbc {
    driver = "com.mysql.jdbc.Driver"
    url = "jdbc:mysql://localhost:8123/log"
    table = "item"
    table_name = "tmp"
    user = "admin"
    password = "admin"
}
```

**Comment by RickyHuo** [comment]
Spark 2.3 works

**Comment by shandowsoftware** [comment]
![image](https://user-images.githubusercontent.com/4735178/61700780-abfd7380-ad6f-11e9-81c0-df0d0f2a8b14.png)

Document is not updated？

**Comment by hery-168** [comment]
spark 2.1 
workdrop 1.3.8 
ClassNotFoundException: org.apache.spark.sql.sources.v2.StreamWriteSupport

**Comment by RickyHuo** [comment]
https://github.com/InterestingLab/waterdrop/releases/tag/v1.4.0 

1.4.0 后，会提供两种编译版本。 请下载with-spark版本以兼容spark2.2
