### ISSUE TITLE
kakfa->hdfs 产生很多小文件

### ISSUE THREAD

**Issue by celestewang1026** [InterestingLab/waterdrop#350]
input：kafka
output： hdfs
导致的问题，小数据文件过多，需要手动合并。有什么好的办法或参数配置吗

**Comment by garyelephant** [comment]
有以下几种办法：
（1）调大duration 时间
（2）减少kafka topic partition个数
（3）使用repartition filter （优先使用前两种，这个如果数据量较大会损害性能）

**Comment by celestewang1026** [comment]
> repartition

第2种方法是不能改变的了。第一种方法和第三种方法可以直接在配置文件设置吗

**Comment by garyelephant** [comment]
可以的，第一个设置方式为：

spark {
  spark.streaming.batchDuration = 5 # 单位是秒
}

第三个设置方法：
filter {
   repartition {}
}
