### ISSUE TITLE
backward compatibility with spark 2.2

### ISSUE THREAD

**Issue by slimtom95** [InterestingLab/waterdrop#352]
The latest build seems not working with spark 2.2.

I don't know which release starts breaking backward compatibility, currently I'm using 1.1.4 and losing a lot of features and updates.

Do we like the idea to maintain backward compatibility with spark 2.2?
If not, would you please kindly tell me which late version still has 2.2 supports?

**Comment by garyelephant** [comment]
Is it possible for you to upgrade Spark version >= 2.3.1 ?

**Comment by slimtom95** [comment]
Unfortunately no, I wish I could.

**Comment by RickyHuo** [comment]
Waterdrop 1.2.4 supports spark 2.2 as I konw

**Comment by RickyHuo** [comment]
Waterdrop <= 1.3.3

**Comment by slimtom95** [comment]
Great! It's definitely enough for now.
Thank you guys @RickyHuo @garyelephant
