### ISSUE TITLE
何时发布v1.3.9版本？

### ISSUE THREAD

**Issue by llysjtu** [InterestingLab/waterdrop#355]
我们强需要支持ClickHouse的decimal类型，当前只能自己编译一个临时版本：
https://github.com/InterestingLab/waterdrop/commit/dc98d4e32a58e5f13c9a160dbcb489fd195ae553#diff-424cc36b01a01a15e38d660bd5a80d0d

**Comment by RickyHuo** [comment]
周三 会和新功能一起发布

**Comment by llysjtu** [comment]
今天周三了

**Comment by RickyHuo** [comment]
催更可还行， 加我个微信吧 chodomatte1994
