### ISSUE TITLE
20170904Week TODO

### ISSUE THREAD

**Issue by garyelephant** [InterestingLab/waterdrop#36]
我列举一下本周可以做的事情：

(1) Filter UDF：

```
a) 找到Spark SQL自带的所有UDF列表，看看这些UDF都能做什么，将来我们可以在Waterdrop的文档里引用这些用户可以直接用的UDF；

b) 我们计划实现的那些Filter，能不能同时提供对应的UDF，如果能该怎么做？

c) 我们的Filter与SparkSQL自带的UDF有没有重复，能不能复用。
```

(2) 确定 BaseFilter的最终接口定义；

```
一个思路是把所有的Filter插件整理一遍，看它们需要什么样的BaseFilter接口定义；

另一个思路是想明白，如果将来有一个用户要开发他自己的插件，他该如何利用BaseFilter的接口开发出自己的插件。
```

(3) 在流程代码中支持多个 input, output

(4) [先搞定前3个再看此条] 确定BaseInput, BaseOutput的接口定义，这个涉及到几个麻烦的技术点，下周再跟你说。

**Comment by RickyHuo** [comment]
https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/functions.scala

**Comment by RickyHuo** [comment]
针对（1） b)

udf实现方式
```
sqlContext.udf.register("strLen", (s:String) => s.length)
sqlContext.sql("select strlen(a) as lens from table")
```

filters实现方式
```
val strLen = udf((s:String) => s.length)
df.withColumn("lens", strLen($"a"))
```

**Comment by RickyHuo** [comment]
## 问题一

为了在sql中使用udf，需要在整个项目初始化阶段register所有我们可以提供的方法（filterObj.singleFunc），目前我认为有两种方法

* 获取package `org.interestinglab.waterdrop.filter`下所有的class文件名，利用Class.forName反射
这么做的问题有两个
    - 并不是所有的filter都能够提供对应的udf，例如Split这种需要根据配置文件参数处理的
    - 相关方法获取packages下class文件名结果并不能直接使用需要过滤
    ```
    baseFilter.scala
    Split$$anonfun$1.scala
    Split$$anonfun$2.scala
    Split.scala
    ...
    ```
* 利用ANTLR4的全部变量
    @garyelephant 帮忙评估一下


## 问题二
> BaseFilter接口如何定义？

当前为了使用withColumn方式需要定义一个方法，我想把这个方法接口`singleFunc`在BaseFilter中定义，因为大部分插件都会用到这个方法，但是有个问题是`singleFunc`在不同的插件中返回值类型是不一样的，那么这种类型的接口如何定义？

**Comment by RickyHuo** [comment]
问题二已经没问题了。

问题一我考虑的出发点是，用户的需求配置如下：
```
inputs {
}
filters {
    sql {
         table = 'my_table'
         sql = "select Split(a, b, c) as key1 from my_table"
    }
}
outputs{
}
```

`Split`方法在filter列表里面是存在的， 但是`Split`并不是`UDF`，所以运行会有报错。
这种需求需要满足吗？

**Comment by garyelephant** [comment]
并不是每个filter，必须注册为udf，这个完全看filter开发者的意愿。如果注册了，就在filter的文档里面写明对应的udf的名称即可。

**Comment by garyelephant** [comment]
@RickyHuo 问题一

直接可用的方案：

java service loader／Service provider interface(s) (SPI)机制: https://www.javacodegeeks.com/2012/12/how-to-create-extensible-java-applications.html, http://literatejava.com/extensibility/java-serviceloader-extensible-applications/, http://www.logicbig.com/tutorials/core-java-tutorial/java-se-api/service-loader/, https://stackoverflow.com/a/45604272/1145750, https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html, https://docs.oracle.com/javase/tutorial/ext/basics/spi.html#define-the-service-provider-interface

org.reflections库： https://github.com/ronmamo/reflections

Apache Commons库：http://commons.apache.org/proper/commons-lang/javadocs/api-release/org/apache/commons/lang3/ClassUtils.html
