### ISSUE TITLE
json嵌套解析问题

### ISSUE THREAD

**Issue by zjybeijing** [InterestingLab/waterdrop#370]
示例数据：
{"name": "waterdrop", "data": {"type": "json", "tag": "test"}}

输出：
filter {
    json {
        source_field = 'raw_message'
    }
}
output {
    stdout {}
}

+------------+---------+
|data        |name     |
+------------+---------+
|[test, json]|waterdrop|

上面的data解析成数组[]的形式区分不出对应的key是哪个，对于嵌套更多层的更加不便于使用
data解析成：{"type": "json", "tag": "test"} 这样应该便于使用，只解析第一层级的

**Comment by RickyHuo** [comment]
@zjybeijing  数组[]只是显示的问题， 可以尝试以下

```
stdout {
    serializer = "json"
}
```

**Comment by zjybeijing** [comment]
使用Structured Streaming的方式定义schema={\"name\": \"waterdrop\", \"data\": \"string\"}}  得到的data值就是{"type": "json", "tag": "test"}
