### ISSUE TITLE
waterterdrop能否支持递归遍历子目录

### ISSUE THREAD

**Issue by a1158420056** [InterestingLab/waterdrop#377]
有时我们的数据会按时间分区存在不同的目录，如2018/1 ,  2018/2 ... 2018/12等12个目录。我已经尝试过，在input中，将hdfs路径设置为2018/1，可以读取该目录下的所有文件。但是，当我设置成路径为2018时，waterdrop无法遍历子目录下的文件，即无法读取1-12目录里面的内容。
        有没有方法可能进行这种设置，或者能不能提供一种方式支持文件目录的读取呢？比如，输入目录路径，指定读取的深度，提供正则来过滤读取的文件名。

**Comment by garyelephant** [comment]
目录路径指定为   2018/*/* 这样试试，使用通配符

**Comment by a1158420056** [comment]
> 目录路径指定为 2018/*/* 这样试试，使用通配符

刚试了一下，可以读取，目前应该是可以用了，就是觉得看着有点奇怪，感谢回答

**Comment by xuxudede** [comment]
怎么我这边用通配符，如果匹配到两个以上文件就会报 range: 268435456-402653184, partition values: [empty row]

**Comment by a1158420056** [comment]
> 怎么我这边用通配符，如果匹配到两个以上文件就会报 range: 268435456-402653184, partition values: [empty row]

不太清楚，我这边类似这样的目录
dir1
   file1
   file2
   dir2
      file3
使用*/*可以读取到file1 file2 file3

**Comment by xuxudede** [comment]
你用的是什么版本，配置文件可以发来看下吗

**Comment by a1158420056** [comment]
> 你用的是什么版本，配置文件可以发来看下吗

就是用的最新的waterdrop
hdfs{
        path="hdfs://host:port/test/*"
        format="text"
        result_table_name="waterdrop_test"
  }
