### ISSUE TITLE
java.lang.String cannot be cast to java.math.BigDecimal

### ISSUE THREAD

**Issue by xjs513** [InterestingLab/waterdrop#382]
数据在文件中，金额的格式是：10.00
ClickHouse 定义的金额是 Decimal(18, 2)
然后导入数据报如题异常，请问如何处理

**Comment by RickyHuo** [comment]
需要在filter阶段转换数据结构。

Decimal 格式的数据， 使用sql 插件转换， CAST(source AS DECIMAL(P, S))

详情参考 https://interestinglab.github.io/waterdrop/#/zh-cn/configuration/output-plugins/Clickhouse?id=clickhouse%e7%b1%bb%e5%9e%8b%e5%af%b9%e7%85%a7%e8%a1%a8
