### ISSUE TITLE
input插件的"result_table_name"

### ISSUE THREAD

**Issue by DengHuoLanShanCherry** [InterestingLab/waterdrop#417]
官方文档上input插件的"result_table_name" required显示为"yes","table_name"显示required为"no",但是当我只配置了"result_table_name"后却报了如下错误,使用的版本为1.4.2
![image](https://user-images.githubusercontent.com/36819187/70846860-c22fdb80-1e98-11ea-994f-41e2d6eb0f5f.png)
![image](https://user-images.githubusercontent.com/36819187/70846870-db388c80-1e98-11ea-9fdd-ab0dc679c6bc.png)
![image](https://user-images.githubusercontent.com/36819187/70846878-f7d4c480-1e98-11ea-9fde-d121199427f2.png)

**Comment by RickyHuo** [comment]
#466
