### ISSUE TITLE
IDEA中怎么运行程序呢

### ISSUE THREAD

**Issue by cs3163077** [InterestingLab/waterdrop#455]

**Comment by RickyHuo** [comment]
![image](https://user-images.githubusercontent.com/18550072/73910481-745cb000-48ea-11ea-8c5f-014f37c11e5d.png)

**Comment by cs3163077** [comment]
![image](https://user-images.githubusercontent.com/13974148/74079950-29bd6e00-4a79-11ea-9670-820133df0fb0.png)

**Comment by cs3163077** [comment]
![MA_ _U 3})5B7N)JVK~K7~S](https://user-images.githubusercontent.com/13974148/74080040-ad2b8f00-4a7a-11ea-8d26-85fe31071fc7.png)

waterdrop-2.0.0-pre一直报
"C:\Program Files\Java\jdk1.8.0_131\bin\java.exe" -Dspark.master=local "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2018.3.5\lib\idea_rt.jar=49829:C:\Program Files\JetBrains\IntelliJ IDEA 2018.3.5\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_131\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\rt.jar;F:\工作\waterdrop-2.0.0-pre\waterdrop-core\target\classes;C:\Users\Administrator\.m2\repository\com\github\scopt\scopt_2.11\3.7.1\scopt_2.11-3.7.1.jar;C:\Users\Administrator\.m2\repository\org\scala-lang\scala-library\2.11.12\scala-library-2.11.12.jar;F:\工作\waterdrop-2.0.0-pre\waterdrop-spark-api\target\classes;F:\工作\waterdrop-2.0.0-pre\plugin-spark-source-kafka\target\classes;C:\Users\Administrator\.m2\repository\org\apache\spark\spark-streaming-kafka-0-10_2.11\2.4.0\spark-streaming-kafka-0-10_2.11-2.4.0.jar;C:\Users\Administrator\.m2\repository\org\apache\kafka\kafka-clients\2.0.0\kafka-clients-2.0.0.jar;F:\工作\waterdrop-2.0.0-pre\plugin-spark-source-fake\target\classes;F:\工作\waterdrop-2.0.0-pre\plugin-spark-source-socket\target\classes;F:\工作\waterdrop-2.0.0-pre\plugin-spark-source-jdbc\target\classes;C:\Users\Administrator\.m2\repository\mysql\mysql-connector-java\5.1.46\mysql-connector-java-5.1.46.jar;F:\工作\waterdrop-2.0.0-pre\plugin-spark-source-elasticsearch\target\classes;C:\Users\Administrator\.m2\repository\org\elasticsearch\elasticsearch-spark-20_2.11\6.8.3\elasticsearch-spark-20_2.11-6.8.3.jar;F:\工作\waterdrop-2.0.0-pre\plugin-spark-transform-sql\target\classes;F:\工作\waterdrop-2.0.0-pre\plugin-spark-transform-json\target\classes;F:\工作\waterdrop-2.0.0-pre\plugin-spark-transform-split\target\classes;F:\工作\waterdrop-2.0.0-pre\plugin-spark-sink-console\target\classes;F:\工作\waterdrop-2.0.0-pre\waterdrop-flink-api\target\classes;C:\Users\Administrator\.m2\repository\org\apache\flink\flink-connector-kafka_2.11\1.9.0\flink-connector-kafka_2.11-1.9.0.jar;C:\Users\Administrator\.m2\repository\org\apache\flink\flink-connector-kafka-base_2.11\1.9.0\flink-connector-kafka-base_2.11-1.9.0.jar;C:\Users\Administrator\.m2\repository\org\apache\flink\flink-json\1.9.0\flink-json-1.9.0.jar;C:\Users\Administrator\.m2\repository\org\apache\flink\flink-csv\1.9.0\flink-csv-1.9.0.jar;C:\Users\Administrator\.m2\repository\org\apache\flink\flink-jdbc_2.11\1.9.0\flink-jdbc_2.11-1.9.0.jar;C:\Users\Administrator\.m2\repository\org\apache\flink\flink-avro\1.9.0\flink-avro-1.9.0.jar;C:\Users\Administrator\.m2\repository\org\apache\flink\flink-orc_2.11\1.9.0\flink-orc_2.11-1.9.0.jar;C:\Users\Administrator\.m2\repository\org\apache\orc\orc-core\1.4.3\orc-core-1.4.3.jar;C:\Users\Administrator\.m2\repository\org\apache\hive\hive-storage-api\2.2.1\hive-storage-api-2.2.1.jar;C:\Users\Administrator\.m2\repository\org\apache\flink\flink-parquet_2.11\1.9.0\flink-parquet_2.11-1.9.0.jar;C:\Users\Administrator\.m2\repository\org\apache\flink\flink-statebackend-rocksdb_2.11\1.9.0\flink-statebackend-rocksdb_2.11-1.9.0.jar;C:\Users\Administrator\.m2\repository\com\data-artisans\frocksdbjni\5.17.2-artisans-1.0\frocksdbjni-5.17.2-artisans-1.0.jar;F:\工作\waterdrop-2.0.0-pre\plugin-spark-sink-elasticsearch\target\classes;F:\工作\waterdrop-2.0.0-pre\plugin-spark-sink-clickhouse\target\classes;C:\Users\Administrator\.m2\repository\ru\yandex\clickhouse\clickhouse-jdbc\0.2\clickhouse-jdbc-0.2.jar;C:\Users\Administrator\.m2\repository\org\apache\httpcomponents\httpclient\4.5.2\httpclient-4.5.2.jar;C:\Users\Administrator\.m2\repository\org\apache\httpcomponents\httpcore\4.4.4\httpcore-4.4.4.jar;C:\Users\Administrator\.m2\repository\org\apache\httpcomponents\httpmime\4.5.2\httpmime-4.5.2.jar;C:\Users\Administrator\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.7.3\jackson-core-2.7.3.jar;C:\Users\Administrator\.m2\repository\com\google\guava\guava\19.0\guava-19.0.jar;C:\Users\Administrator\.m2\repository\javax\xml\bind\jaxb-api\2.3.0\jaxb-api-2.3.0.jar;F:\工作\waterdrop-2.0.0-pre\plugin-spark-sink-file\target\classes;F:\工作\waterdrop-2.0.0-pre\plugin-flink-source-kafka\target\classes;F:\工作\waterdrop-2.0.0-pre\plugin-flink-sink-kafka\target\classes;F:\工作\waterdrop-2.0.0-pre\plugin-flink-transform-sql\target\classes;F:\工作\waterdrop-2.0.0-pre\plugin-flink-transform-split\target\classes;F:\工作\waterdrop-2.0.0-pre\plugin-flink-transform-table2datasteam\target\classes;F:\工作\waterdrop-2.0.0-pre\plugin-flink-transform-datastream2table\target\classes;F:\工作\waterdrop-2.0.0-pre\plugin-flink-sink-console\target\classes;F:\工作\waterdrop-2.0.0-pre\plugin-flink-sink-jdbc\target\classes;F:\工作\waterdrop-2.0.0-pre\plugin-flink-source-fake\target\classes;F:\工作\waterdrop-2.0.0-pre\plugin-flink-source-socket\target\classes;F:\工作\waterdrop-2.0.0-pre\plugin-flink-source-file\target\classes;C:\Users\Administrator\.m2\repository\org\apache\flink\flink-shaded-hadoop-2\2.7.5-7.0\flink-shaded-hadoop-2-2.7.5-7.0.jar;C:\Users\Administrator\.m2\repository\org\apache\commons\commons-compress\1.18\commons-compress-1.18.jar;C:\Users\Administrator\.m2\repository\com\thoughtworks\paranamer\paranamer\2.7\paranamer-2.7.jar;C:\Users\Administrator\.m2\repository\org\tukaani\xz\1.5\xz-1.5.jar;C:\Users\Administrator\.m2\repository\commons-cli\commons-cli\1.3.1\commons-cli-1.3.1.jar;C:\Users\Administrator\.m2\repository\xmlenc\xmlenc\0.52\xmlenc-0.52.jar;C:\Users\Administrator\.m2\repository\commons-codec\commons-codec\1.10\commons-codec-1.10.jar;C:\Users\Administrator\.m2\repository\commons-io\commons-io\2.4\commons-io-2.4.jar;C:\Users\Administrator\.m2\repository\commons-collections\commons-collections\3.2.2\commons-collections-3.2.2.jar;C:\Users\Administrator\.m2\repository\javax\servlet\servlet-api\2.5\servlet-api-2.5.jar;C:\Users\Administrator\.m2\repository\org\mortbay\jetty\jetty-sslengine\6.1.26\jetty-sslengine-6.1.26.jar;C:\Users\Administrator\.m2\repository\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;C:\Users\Administrator\.m2\repository\com\jamesmurty\utils\java-xmlbuilder\0.4\java-xmlbuilder-0.4.jar;C:\Users\Administrator\.m2\repository\commons-lang\commons-lang\2.6\commons-lang-2.6.jar;C:\Users\Administrator\.m2\repository\commons-configuration\commons-configuration\1.7\commons-configuration-1.7.jar;C:\Users\Administrator\.m2\repository\commons-digester\commons-digester\1.8.1\commons-digester-1.8.1.jar;C:\Users\Administrator\.m2\repository\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar;C:\Users\Administrator\.m2\repository\org\apache\directory\server\apacheds-kerberos-codec\2.0.0-M15\apacheds-kerberos-codec-2.0.0-M15.jar;C:\Users\Administrator\.m2\repository\org\apache\directory\server\apacheds-i18n\2.0.0-M15\apacheds-i18n-2.0.0-M15.jar;C:\Users\Administrator\.m2\repository\org\apache\directory\api\api-asn1-api\1.0.0-M20\api-asn1-api-1.0.0-M20.jar;C:\Users\Administrator\.m2\repository\org\apache\directory\api\api-util\1.0.0-M20\api-util-1.0.0-M20.jar;C:\Users\Administrator\.m2\repository\com\jcraft\jsch\0.1.54\jsch-0.1.54.jar;C:\Users\Administrator\.m2\repository\org\apache\htrace\htrace-core\3.1.0-incubating\htrace-core-3.1.0-incubating.jar;C:\Users\Administrator\.m2\repository\commons-beanutils\commons-beanutils\1.9.3\commons-beanutils-1.9.3.jar;C:\Users\Administrator\.m2\repository\commons-daemon\commons-daemon\1.0.13\commons-daemon-1.0.13.jar;C:\Users\Administrator\.m2\repository\xerces\xercesImpl\2.9.1\xercesImpl-2.9.1.jar;C:\Users\Administrator\.m2\repository\org\fusesource\leveldbjni\leveldbjni-all\1.8\leveldbjni-all-1.8.jar;C:\Users\Administrator\.m2\repository\javax\xml\stream\stax-api\1.0-2\stax-api-1.0-2.jar;C:\Users\Administrator\.m2\repository\com\sun\jersey\jersey-client\1.9\jersey-client-1.9.jar;C:\Users\Administrator\.m2\repository\org\apache\parquet\parquet-avro\1.10.0\parquet-avro-1.10.0.jar;C:\Users\Administrator\.m2\repository\org\apache\parquet\parquet-format\2.4.0\parquet-format-2.4.0.jar;C:\Users\Administrator\.m2\repository\it\unimi\dsi\fastutil\7.0.13\fastutil-7.0.13.jar;F:\工作\waterdrop-2.0.0-pre\plugin-flink-source-jdbc\target\classes;F:\工作\waterdrop-2.0.0-pre\plugin-flink-sink-file\target\classes;F:\工作\waterdrop-2.0.0-pre\plugin-flink-sink-elasticsearch\target\classes;C:\Users\Administrator\.m2\repository\org\apache\flink\flink-connector-elasticsearch6_2.11\1.9.0\flink-connector-elasticsearch6_2.11-1.9.0.jar;C:\Users\Administrator\.m2\repository\org\apache\flink\flink-connector-elasticsearch-base_2.11\1.9.0\flink-connector-elasticsearch-base_2.11-1.9.0.jar;C:\Users\Administrator\.m2\repository\org\elasticsearch\client\elasticsearch-rest-high-level-client\6.3.1\elasticsearch-rest-high-level-client-6.3.1.jar;C:\Users\Administrator\.m2\repository\org\elasticsearch\client\elasticsearch-rest-client\6.3.1\elasticsearch-rest-client-6.3.1.jar;C:\Users\Administrator\.m2\repository\org\apache\httpcomponents\httpasyncclient\4.1.2\httpasyncclient-4.1.2.jar;C:\Users\Administrator\.m2\repository\org\apache\httpcomponents\httpcore-nio\4.4.5\httpcore-nio-4.4.5.jar;C:\Users\Administrator\.m2\repository\org\elasticsearch\plugin\aggs-matrix-stats-client\6.3.1\aggs-matrix-stats-client-6.3.1.jar;C:\Users\Administrator\.m2\repository\org\apache\logging\log4j\log4j-to-slf4j\2.9.1\log4j-to-slf4j-2.9.1.jar;C:\Users\Administrator\.m2\repository\org\apache\logging\log4j\log4j-api\2.9.1\log4j-api-2.9.1.jar;C:\Users\Administrator\.m2\repository\org\elasticsearch\client\transport\6.3.1\transport-6.3.1.jar;C:\Users\Administrator\.m2\repository\org\elasticsearch\elasticsearch\6.3.1\elasticsearch-6.3.1.jar;C:\Users\Administrator\.m2\repository\org\elasticsearch\elasticsearch-core\6.3.1\elasticsearch-core-6.3.1.jar;C:\Users\Administrator\.m2\repository\org\elasticsearch\elasticsearch-secure-sm\6.3.1\elasticsearch-secure-sm-6.3.1.jar;C:\Users\Administrator\.m2\repository\org\elasticsearch\elasticsearch-x-content\6.3.1\elasticsearch-x-content-6.3.1.jar;C:\Users\Administrator\.m2\repository\org\yaml\snakeyaml\1.17\snakeyaml-1.17.jar;C:\Users\Administrator\.m2\repository\com\fasterxml\jackson\dataformat\jackson-dataformat-smile\2.8.10\jackson-dataformat-smile-2.8.10.jar;C:\Users\Administrator\.m2\repository\com\fasterxml\jackson\dataformat\jackson-dataformat-yaml\2.8.10\jackson-dataformat-yaml-2.8.10.jar;C:\Users\Administrator\.m2\repository\com\fasterxml\jackson\dataformat\jackson-dataformat-cbor\2.8.10\jackson-dataformat-cbor-2.8.10.jar;C:\Users\Administrator\.m2\repository\org\apache\lucene\lucene-core\7.3.1\lucene-core-7.3.1.jar;C:\Users\Administrator\.m2\repository\org\apache\lucene\lucene-analyzers-common\7.3.1\lucene-analyzers-common-7.3.1.jar;C:\Users\Administrator\.m2\repository\org\apache\lucene\lucene-backward-codecs\7.3.1\lucene-backward-codecs-7.3.1.jar;C:\Users\Administrator\.m2\repository\org\apache\lucene\lucene-grouping\7.3.1\lucene-grouping-7.3.1.jar;C:\Users\Administrator\.m2\repository\org\apache\lucene\lucene-highlighter\7.3.1\lucene-highlighter-7.3.1.jar;C:\Users\Administrator\.m2\repository\org\apache\lucene\lucene-join\7.3.1\lucene-join-7.3.1.jar;C:\Users\Administrator\.m2\repository\org\apache\lucene\lucene-memory\7.3.1\lucene-memory-7.3.1.jar;C:\Users\Administrator\.m2\repository\org\apache\lucene\lucene-misc\7.3.1\lucene-misc-7.3.1.jar;C:\Users\Administrator\.m2\repository\org\apache\lucene\lucene-queries\7.3.1\lucene-queries-7.3.1.jar;C:\Users\Administrator\.m2\repository\org\apache\lucene\lucene-queryparser\7.3.1\lucene-queryparser-7.3.1.jar;C:\Users\Administrator\.m2\repository\org\apache\lucene\lucene-sandbox\7.3.1\lucene-sandbox-7.3.1.jar;C:\Users\Administrator\.m2\repository\org\apache\lucene\lucene-spatial\7.3.1\lucene-spatial-7.3.1.jar;C:\Users\Administrator\.m2\repository\org\apache\lucene\lucene-spatial-extras\7.3.1\lucene-spatial-extras-7.3.1.jar;C:\Users\Administrator\.m2\repository\org\apache\lucene\lucene-spatial3d\7.3.1\lucene-spatial3d-7.3.1.jar;C:\Users\Administrator\.m2\repository\org\apache\lucene\lucene-suggest\7.3.1\lucene-suggest-7.3.1.jar;C:\Users\Administrator\.m2\repository\org\elasticsearch\elasticsearch-cli\6.3.1\elasticsearch-cli-6.3.1.jar;C:\Users\Administrator\.m2\repository\net\sf\jopt-simple\jopt-simple\5.0.2\jopt-simple-5.0.2.jar;C:\Users\Administrator\.m2\repository\com\tdunning\t-digest\3.2\t-digest-3.2.jar;C:\Users\Administrator\.m2\repository\org\hdrhistogram\HdrHistogram\2.1.9\HdrHistogram-2.1.9.jar;C:\Users\Administrator\.m2\repository\org\elasticsearch\jna\4.5.1\jna-4.5.1.jar;C:\Users\Administrator\.m2\repository\org\elasticsearch\plugin\transport-netty4-client\6.3.1\transport-netty4-client-6.3.1.jar;C:\Users\Administrator\.m2\repository\io\netty\netty-buffer\4.1.16.Final\netty-buffer-4.1.16.Final.jar;C:\Users\Administrator\.m2\repository\io\netty\netty-codec\4.1.16.Final\netty-codec-4.1.16.Final.jar;C:\Users\Administrator\.m2\repository\io\netty\netty-codec-http\4.1.16.Final\netty-codec-http-4.1.16.Final.jar;C:\Users\Administrator\.m2\repository\io\netty\netty-common\4.1.16.Final\netty-common-4.1.16.Final.jar;C:\Users\Administrator\.m2\repository\io\netty\netty-handler\4.1.16.Final\netty-handler-4.1.16.Final.jar;C:\Users\Administrator\.m2\repository\io\netty\netty-resolver\4.1.16.Final\netty-resolver-4.1.16.Final.jar;C:\Users\Administrator\.m2\repository\io\netty\netty-transport\4.1.16.Final\netty-transport-4.1.16.Final.jar;C:\Users\Administrator\.m2\repository\org\elasticsearch\plugin\reindex-client\6.3.1\reindex-client-6.3.1.jar;C:\Users\Administrator\.m2\repository\org\elasticsearch\plugin\lang-mustache-client\6.3.1\lang-mustache-client-6.3.1.jar;C:\Users\Administrator\.m2\repository\com\github\spullara\mustache\java\compiler\0.9.3\compiler-0.9.3.jar;C:\Users\Administrator\.m2\repository\org\elasticsearch\plugin\percolator-client\6.3.1\percolator-client-6.3.1.jar;C:\Users\Administrator\.m2\repository\org\elasticsearch\plugin\parent-join-client\6.3.1\parent-join-client-6.3.1.jar;C:\Users\Administrator\.m2\repository\org\elasticsearch\plugin\rank-eval-client\6.3.1\rank-eval-client-6.3.1.jar;C:\Users\Administrator\.m2\repository\org\apache\spark\spark-tags_2.11\2.4.0\spark-tags_2.11-2.4.0.jar;C:\Users\Administrator\.m2\repository\org\spark-project\spark\unused\1.0.0\unused-1.0.0.jar;C:\Users\Administrator\.m2\repository\org\apache\avro\avro\1.8.2\avro-1.8.2.jar;C:\Users\Administrator\.m2\repository\org\codehaus\jackson\jackson-core-asl\1.9.13\jackson-core-asl-1.9.13.jar;C:\Users\Administrator\.m2\repository\org\codehaus\jackson\jackson-mapper-asl\1.9.13\jackson-mapper-asl-1.9.13.jar;C:\Users\Administrator\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.6.7\jackson-annotations-2.6.7.jar;C:\Users\Administrator\.m2\repository\javax\activation\activation\1.1.1\activation-1.1.1.jar;C:\Users\Administrator\.m2\repository\org\apache\zookeeper\zookeeper\3.4.6\zookeeper-3.4.6.jar;C:\Users\Administrator\.m2\repository\org\apache\commons\commons-math3\3.4.1\commons-math3-3.4.1.jar;C:\Users\Administrator\.m2\repository\com\google\code\findbugs\jsr305\1.3.9\jsr305-1.3.9.jar;C:\Users\Administrator\.m2\repository\org\slf4j\slf4j-api\1.7.16\slf4j-api-1.7.16.jar;C:\Users\Administrator\.m2\repository\log4j\log4j\1.2.17\log4j-1.2.17.jar;C:\Users\Administrator\.m2\repository\org\slf4j\slf4j-log4j12\1.7.16\slf4j-log4j12-1.7.16.jar;C:\Users\Administrator\.m2\repository\org\xerial\snappy\snappy-java\1.1.7.1\snappy-java-1.1.7.1.jar;C:\Users\Administrator\.m2\repository\org\lz4\lz4-java\1.4.0\lz4-java-1.4.0.jar;C:\Users\Administrator\.m2\repository\commons-net\commons-net\3.1\commons-net-3.1.jar;C:\Users\Administrator\.m2\repository\io\netty\netty\3.9.9.Final\netty-3.9.9.Final.jar;C:\Users\Administrator\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.6.7.1\jackson-databind-2.6.7.1.jar;C:\Users\Administrator\.m2\repository\com\google\protobuf\protobuf-java\2.5.0\protobuf-java-2.5.0.jar;C:\Users\Administrator\.m2\repository\io\airlift\aircompressor\0.10\aircompressor-0.10.jar;C:\Users\Administrator\.m2\repository\org\apache\parquet\parquet-column\1.10.0\parquet-column-1.10.0.jar;C:\Users\Administrator\.m2\repository\org\apache\parquet\parquet-common\1.10.0\parquet-common-1.10.0.jar;C:\Users\Administrator\.m2\repository\org\apache\parquet\parquet-encoding\1.10.0\parquet-encoding-1.10.0.jar;C:\Users\Administrator\.m2\repository\org\apache\parquet\parquet-hadoop\1.10.0\parquet-hadoop-1.10.0.jar;C:\Users\Administrator\.m2\repository\org\apache\parquet\parquet-jackson\1.10.0\parquet-jackson-1.10.0.jar;C:\Users\Administrator\.m2\repository\joda-time\joda-time\2.9.9\joda-time-2.9.9.jar;C:\Users\Administrator\.m2\repository\com\carrotsearch\hppc\0.7.2\hppc-0.7.2.jar;C:\Users\Administrator\.m2\repository\net\jpountz\lz4\lz4\1.3.0\lz4-1.3.0.jar;C:\Users\Administrator\.m2\repository\org\apache\flink\force-shading\1.9.0\force-shading-1.9.0.jar;C:\Users\Administrator\.m2\repository\org\codehaus\janino\janino\3.0.9\janino-3.0.9.jar;C:\Users\Administrator\.m2\repository\org\codehaus\janino\commons-compiler\3.0.9\commons-compiler-3.0.9.jar" io.github.interestinglab.waterdrop.Waterdrop --master local --deploy-mode client --config ./config/spark.batch.conf.template
java.lang.NoClassDefFoundError: io/github/interestinglab/waterdrop/common/config/ConfigRuntimeException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: io.github.interestinglab.waterdrop.common.config.ConfigRuntimeException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" 
Process finished with exit code 1
不知道是不是环境的问题

**Comment by liujin0719** [comment]
> ![MA_ _U 3})5B7N)JVKK7S](https://user-images.githubusercontent.com/13974148/74080040-ad2b8f00-4a7a-11ea-8d26-85fe31071fc7.png)
> 
> waterdrop-2.0.0-pre一直报
> Error: A JNI error has occurred, please check your installation and try again
> Exception in thread "main"
> Process finished with exit code 1
> 不知道是不是环境的问题

我也遇到了这个问题，请问现在解决了吗？

**Comment by liujin0719** [comment]
已解决，如下图所示，需要勾上这个选项
![image](https://user-images.githubusercontent.com/40172723/74231801-62bc4380-4d02-11ea-9af5-79b92de8b617.png)

**Comment by RickyHuo** [comment]
抱歉，最开始回复欠妥。

我回复的是基于V1版本的Waterdrop。

V2版本支持Flink的Waterdrop，需要勾选 `Include dependencies with "Provided" scope`

**Comment by wangxiangyu** [comment]
V2版本支持Flink的Waterdrop，需要勾选` Include dependencies with "Provided" scope`

似乎这个还不够，还需要添加这些信息到pom

```
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-runtime_2.11</artifactId>
            <version>${flink.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-streaming-java_2.11</artifactId>
            <version>${flink.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-java</artifactId>
            <version>${flink.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-table-api-java-bridge_2.11</artifactId>
            <version>${flink.version}</version>
        </dependency>
        
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-table-planner_2.11</artifactId>
            <version>${flink.version}</version>
        </dependency>
```

同时，注意idea的scala版本要使用2.11.8

**Comment by zhongjiajie** [comment]
> V2版本支持Flink的Waterdrop，需要勾选` Include dependencies with "Provided" scope`
> 
> 似乎这个还不够，还需要添加这些信息到pom
> 
> ```
>         <dependency>
>             <groupId>org.apache.flink</groupId>
>             <artifactId>flink-runtime_2.11</artifactId>
>             <version>${flink.version}</version>
>         </dependency>
> 
>         <dependency>
>             <groupId>org.apache.flink</groupId>
>             <artifactId>flink-streaming-java_2.11</artifactId>
>             <version>${flink.version}</version>
>         </dependency>
> 
>         <dependency>
>             <groupId>org.apache.flink</groupId>
>             <artifactId>flink-java</artifactId>
>             <version>${flink.version}</version>
>         </dependency>
> 
>         <dependency>
>             <groupId>org.apache.flink</groupId>
>             <artifactId>flink-table-api-java-bridge_2.11</artifactId>
>             <version>${flink.version}</version>
>         </dependency>
>         
>         <dependency>
>             <groupId>org.apache.flink</groupId>
>             <artifactId>flink-table-planner_2.11</artifactId>
>             <version>${flink.version}</version>
>         </dependency>
> ```
> 
> 同时，注意idea的scala版本要使用2.11.8

@CalvinKirs Did you have time to check this issue?
