### ISSUE TITLE
在配置文件中指定 指定参数spark.yarn.queue不生效

### ISSUE THREAD

**Issue by plum-wine** [InterestingLab/waterdrop#458]
spark version: spark-2.1.0-bin-hadoop2.7
water version: waterdrop-1.4.2

启动方式: ./bin/start-waterdrop.sh --master yarn --deploy-mode cluster --config test.conf

conf:
spark {
  spark.yarn.queue = "myqueue"
  spark.app.name = "Waterdrop"
  spark.executor.instances = 30
  spark.executor.cores = 30
  spark.sql.catalogImplementation = "hive"
  spark.executor.memory = "30g"
}

log
org.apache.hadoop.yarn.exceptions.YarnException: Failed to submit application_1576141534408_6829426 to YARN : User xxx cannot submit applications to queue root.default

**Comment by RickyHuo** [comment]
spark {
	  # You can set spark configuration here
	  # Waterdrop defined streaming batch duration in seconds
	  spark.streaming.batchDuration = 5

	  # see available properties defined by spark: https://spark.apache.org/docs/latest/configuration.html#available-properties
	  spark.app.name = "Waterdrop"
	  spark.executor.instances = 2
	  spark.executor.cores = 1
	  spark.executor.memory = "1g"
      # ------
	  spark.yarn.queue = "xx"
	}

spark.yarn.queue 应该是没有问题的，如果更多信息， 随时反馈

**Comment by RickyHuo** [comment]
#502 这个在v1.5.0会放在启动命令中支持
