### ISSUE TITLE
read CSV format file with header

### ISSUE THREAD

**Issue by wangxiaobing-zm** [InterestingLab/waterdrop#461]
示例如下：
+-----------+-------------+----------+-----------+--------------+-------------------+-------------------+------------------+---------------+--------+-----------+-------------------+-----------+-------------------+----------------+--------------------+--------+------------+--------------+-------------+-----------+-----------+----------+---------+---------+--------------+---------+
|_c0        |_c1          |_c2       |_c3        |_c4           |_c5                |_c6                |_c7               |_c8            |_c9     |_c10       |_c11               |_c12       |_c13               |_c14            |_c15                |_c16    |_c17        |_c18          |_c19         |_c20       |_c21       |_c22      |_c23     |_c24     |_c25          |_c26     |
+-----------+-------------+----------+-----------+--------------+-------------------+-------------------+------------------+---------------+--------+-----------+-------------------+-----------+-------------------+----------------+--------------------+--------+------------+--------------+-------------+-----------+-----------+----------+---------+---------+--------------+---------+
|RELATION_ID|PRODUCT_CODE |ORDER_TYPE|PHONE_NUM  |SERV_CODE     |ORDER_DATE         |VALID_DATE         |EXPIRE_DATE       |RELATION_STATUS|DATA_SRC|CREATE_USER|CREATE_TIME        |UPDATE_USER|UPDATE_TIME        |CRM_PRODUCT_CODE|BASIC_PRODUCT_DOCE  |CDN_TYPE|IN_BLACKLIST|SECOND_CONFIRM|PAY_PHONE_NUM|UNSUBSTATUS|PAY_CHANNEL|PARTNER_ID|CITY_CODE|AUTO_FLAG|DIVERSION_CODE|BILL_FLAG|
|5233674    |null         |0         |15162159659|null          |2015/5/12 20:22:38 |2015/5/12 20:22:38 |null              |1              |null    |618557678  |null               |null       |null               |2413000011      |10800000000000000021|null    |null        |null          |null         |null       |null       |null      |null     |null     |null          |null     |

**Comment by RickyHuo** [comment]
参考以下配置

```
file {
    path = "file:///xxx/nginx.csv"
    result_table_name = "my_dataset"
    options.header = "true"
    format = "csv"
  }
```
