### ISSUE TITLE
hive 数据导入clickhouse数据丢失，原因是在input的pre_sql中加了order by

### ISSUE THREAD

**Issue by LiangZiGe** [InterestingLab/waterdrop#462]
hive 数据导入clickhouse数据丢失，原因是在input的pre_sql中加了order by，亲测多次导入数据远比原hive表少，去掉order by就没问题了。为什么呢？
1.建表语句
CREATE TABLE app.a on cluster zero_db_ck_cluster (
  `x` String, 
  `x1` Int64, 
  `x2` Int64, 
  `x3` Int32, 
  `x4` Int32, 
  `x5` Int32, 
  `x6` Int32, 
  `x7` Int32, 
  `x8` Int32, 
  `x9` Int32, 
  `dt` Date
)ENGINE = ReplicatedMergeTree(
  '/clickhouse/zero_db_ck_cluster/app/tables/a/{shard}',
  '{replica}'
) PARTITION BY (dt)
ORDER BY
  (dt,x7,x8,x3,x4,x6) 
  SETTINGS use_minimalistic_part_header_in_zookeeper = 1

2.pre_sql 
pre_sql = """
      select
       *
      from
        app.a
      where
        dt >= '2019-01-01'
     order by dt,x7,x8,x3,x4,x6
"""

**Comment by RickyHuo** [comment]
多次测试含有order by的pre_sql，每次写入条数一致吗



在 2020-03-19 20:31:16，"良子" <notifications@github.com> 写道：

hive 数据导入clickhouse数据丢失，原因是在input的pre_sql中加了order by，亲测多次导入数据远比原hive表少，去掉order by就没问题了。为什么呢？
1.建表语句
CREATE TABLE app.a on cluster zero_db_ck_cluster (
x String,
x1 Int64,
x2 Int64,
x3 Int32,
x4 Int32,
x5 Int32,
x6 Int32,
x7 Int32,
x8 Int32,
x9 Int32,
dt Date
)ENGINE = ReplicatedMergeTree(
'/clickhouse/zero_db_ck_cluster/app/tables/a/{shard}',
'{replica}'
) PARTITION BY (dt)
ORDER BY
(dt,x7,x8,x3,x4,x6)
SETTINGS use_minimalistic_part_header_in_zookeeper = 1

2.pre_sql
pre_sql = """
select
*
from
app.a
where
dt >= '2019-01-01'
order by dt,x7,x8,x3,x4,x6
"""

**Comment by LiangZiGe** [comment]
> 多次测试含有order by的pre_sql，每次写入条数一致吗 在 2020-03-19 20:31:16，"良子" <notifications@github.com> 写道： hive 数据导入clickhouse数据丢失，原因是在input的pre_sql中加了order by，亲测多次导入数据远比原hive表少，去掉order by就没问题了。为什么呢？ 1.建表语句 CREATE TABLE app.a on cluster zero_db_ck_cluster ( x String, x1 Int64, x2 Int64, x3 Int32, x4 Int32, x5 Int32, x6 Int32, x7 Int32, x8 Int32, x9 Int32, dt Date )ENGINE = ReplicatedMergeTree( '/clickhouse/zero_db_ck_cluster/app/tables/a/{shard}', '{replica}' ) PARTITION BY (dt) ORDER BY (dt,x7,x8,x3,x4,x6) SETTINGS use_minimalistic_part_header_in_zookeeper = 1 2.pre_sql pre_sql = """ select * from app.a where dt >= '2019-01-01' order by dt,x7,x8,x3,x4,x6 """ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
每次都不一致

**Comment by LiangZiGe** [comment]
每次写入条数都不一致

**Comment by LiangZiGe** [comment]
经验证是clickhouse部署配置文件写错了，和waterdrop没关系。
