### ISSUE TITLE
Elasticsearch版本问题

### ISSUE THREAD

**Issue by kukone** [InterestingLab/waterdrop#468]
你好，目前支持的Elasticsearch版本为 >= 2.x 且 < 7.0.0，我的Elasticsearch版本>7.0.0，我该怎么操作。谢谢！

**Comment by RickyHuo** [comment]
我们看一下高版本依赖的兼容性

**Comment by kukone** [comment]
> 我们看一下高版本依赖的兼容性

Thanks

**Comment by kukone** [comment]
> 我们看一下高版本依赖的兼容性

还有一个问题，在v2.x 版本中的Source 插件配置的JDBC中，可以指定查询条件吗？

**Comment by RickyHuo** [comment]
Fixed #473

**Comment by x956606865** [comment]
我这里使用的是2.0.4版本的waterdrop，elasticsearch模块似乎依旧不支持7以上的版本。我使用6.8版本的ES时，能够正常连接使用，但是使用7.5版本的ES时，就会报错，说“Cannot detect ES version”。
请问是不是改的时候忘了更新2.0版本的插件了Orz
