### ISSUE TITLE
wd-v2-baseline 分支用依赖的 wd-config 包不存在

### ISSUE THREAD

**Issue by yangbaiboot** [InterestingLab/waterdrop#472]
waterdrop-wd-v2-baseline/common/pom.xml 该 pom 文件中

```
<dependency>
     <groupId>com.typesafe.config.waterdrop</groupId>
      <artifactId>wd-config</artifactId>
      <version>1.3.3</version>
 </dependency>
```

在 https://mvnrepository.com/ 中拉取不到
唯一找到相似的依赖：

```
<dependency>
    <groupId>com.typesafe</groupId>
    <artifactId>config</artifactId>
    <version>1.3.3</version>
</dependency>
```

如果该依赖是未上传到公共 maven 仓库，麻烦上传一下。

**Comment by RickyHuo** [comment]
@yangbaiboot  https://github.com/InterestingLab/waterdrop/tree/wd-v2-baseline/common/lib/com/typesafe/config/waterdrop/wd-config/1.3.3

**Comment by yangbaiboot** [comment]
> 
> 
> @yangbaiboot https://github.com/InterestingLab/waterdrop/tree/wd-v2-baseline/common/lib/com/typesafe/config/waterdrop/wd-config/1.3.3
> 
> 这个依赖是通过local-repo的方式引入的

收到，多谢！

**Comment by WJustHM** [comment]
Hello  这个本地包是否可以提供源码地址呢

**Comment by RickyHuo** [comment]
@WJustHM https://github.com/InterestingLab/config
