### ISSUE TITLE
ClickHouse存在中文列，导入的时候报错

### ISSUE THREAD

**Issue by yangliu0903** [InterestingLab/waterdrop#476]
由于项目年头比较老，还存在中文列，导入的时候报错：
20/04/30 15:20:32 INFO batch.Clickhouse: insert into ods_hft_sqlserver_bi_kh_manager (?板𸰿??𹠿,浼𼐿𺃯缁𹠿𹳝?灞𽐿𶠿??浼𼐿𺃯缁𹠿𹳝濮𺠿𹳤,浼𼐿𺃯缁𹠿𹳝?𸠿𼰿?风𽳘,浼𼐿𺃯缁𹠿𹳝韬?唤璇𶀿𹠿,浼𼐿𺃯缁𹠿𹳝?𺀿??𶰿??𻰿??𹀬浼𼐿𺃯缁𹠿𹳝?𺀿??𶰿??𻰿𸃢?哄𹠿?𶀬??𹰿?板𹣨灞𻀬remark,guanlibu) values (?,?,?,?,?,?,?,?,?,?)

clickhouse里面的表格结构存在中文列：
DESCRIBE TABLE ods_hft_sqlserver_bi_kh_manager
┌─name───────────────────────┬─type───┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ 地区公司                   │ String │              │                    │         │                  │                │
│ 会员经理所属部门           │ String │              │                    │         │                  │                │
│ 会员经理姓名               │ String │              │                    │         │                  │                │
│ 会员经理手机号码           │ String │              │                    │         │                  │                │
│ 会员经理身份证号           │ String │              │                    │         │                  │                │
│ 会员经理发展的会员姓名     │ String │              │                    │         │                  │                │
│ 会员经理发展的会员手机号码 │ String │              │                    │         │                  │                │
│ 是否新发展                 │ String │              │                    │         │                  │                │
│ remark                     │ String │              │                    │         │                  │                │
│ guanlibu                   │ String │              │                    │         │                  │                │
└────────────────────────────┴────────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘

**Comment by RickyHuo** [comment]
```
CREATE TABLE test.cn (`名字` String, `性别` String) ENGINE = Log

insert into cn (`名字`,`性别`) values ('rickyhuo', '男');

```
