### ISSUE TITLE
Exception in thread "main" java.lang.Exception: org.apache.spark.sql.AnalysisException: Table or view not found: `cc_dw`.`aa`; line 1 pos 14;

### ISSUE THREAD

**Issue by terriblegirl** [InterestingLab/waterdrop#487]
**Waterdrop Version(waterdrop-1.4.3）

A clear version of Waterdrop. 

**Spark Version(spark-2.4.5-bin-hadoop2.7)

A clear version of Spark.

**Java Version(1.8.0_242)

A clear version of Java.

**Waterdrop Config(Waterdrop配置文件)**

Please delete sensitive information(请注意删除敏感信息)

```
spark {
spark.app.name = "Waterdrop"
  spark.executor.instances = 2
  spark.executor.cores = 1
  spark.executor.memory = "1g"
}
input {
hive {
        pre_sql = "select * from cc_dw.aa"
        table_name = "cms_msg"
    }
}
filter {
remove {
        source_field = ["id"]
    }
}
output {
 stdout {
    serializer = "json"
}

}
```

**Screenshots**

**Additional context**

issue：
Exception in thread "main" java.lang.Exception: org.apache.spark.sql.AnalysisException: Table or view not found: `cc_dw`.`aa`; line 1 pos 14;
截图：
![image](https://user-images.githubusercontent.com/48819512/81530114-cd792b80-9392-11ea-8591-53c240d1681d.png)
已经在hive中确认过这张表是存在的并且有数据。
![image](https://user-images.githubusercontent.com/48819512/81530201-fb5e7000-9392-11ea-899c-ebeaef4472d8.png)
hive-site.xml文件也已经放置到spark的conf目录之下了启动spark-sql查询这张表也可以查询到
![image](https://user-images.githubusercontent.com/48819512/81530398-5f813400-9393-11ea-93ff-eed04dd3d8fa.png)

目前已经不知道该继续从哪个角度继续排查请求帮助

**Comment by RickyHuo** [comment]
请参考文档 https://interestinglab.github.io/waterdrop-docs/#/zh-cn/v1/configuration/input-plugins/Hive

```
注意：从waterdrop v1.3.4 开始，使用hive input必须做如下配置：

# Waterdrop 配置文件中的spark section中：

spark {
  ...
  spark.sql.catalogImplementation = "hive"
  ...
}
```
