### ISSUE TITLE
插入clickhouse与hive中的日期数据不一致

### ISSUE THREAD

**Issue by terriblegirl** [InterestingLab/waterdrop#490]
**Waterdrop Version(waterdrop-1.4.3）

A clear version of Waterdrop. 

**Spark Version(spark-2.4.5-bin-hadoop2.7)

A clear version of Spark.

**Java Version(1.8.0_242)

A clear version of Java.

**Waterdrop Config(Waterdrop配置文件)**

Please delete sensitive information(请注意删除敏感信息)
spark {
  spark.app.name = "Waterdrop"
  spark.executor.instances = 2
  spark.executor.cores = 1
  spark.executor.memory = "1g"
  spark.sql.catalogImplementation = "hive"
}
input {
    hive {
        pre_sql = "select city_name,pinyin,city_code,area_code,weather_code,to_date(start_date) from cc_dw.t_dim_city"
##to_date(start_date)是为了把date类型转换成string类型
        table_name = "cms_msg"
    }

}
filter {
remove {
        source_field = ["weather_code"]
    }
  }

output {
    clickhouse {
        host = "IP:8123"
        database = "waterdrop"
        table = "t_dim_city"
        fields = ["city_name", "pinyin", "city_code", "area_code", "start_date"]
        username = ""
        password = ""
    }
}

**Screenshots**

**Additional context**
ISSUE：在从hive到clickhouse的过程中没有报错但是最后的时间数据出现问题

截图：
clickhouse中的数据
![image](https://user-images.githubusercontent.com/48819512/81635329-931b9700-9443-11ea-89c6-79625bb47134.png)

hive中的数据
![image](https://user-images.githubusercontent.com/48819512/81635212-459f2a00-9443-11ea-9393-e54ff0aea9ee.png)

为了查看问题又用output查看数据

hive的建表情况
![image](https://user-images.githubusercontent.com/48819512/81532837-aec96380-9397-11ea-9efe-674ed4b2fb45.png)
clickhouse的建表情况
![image](https://user-images.githubusercontent.com/48819512/81634956-96625300-9442-11ea-89ce-deedde9f8f6c.png)

最终也就是说hive的数据跟output的数据是一致的，但是插入到clickhouse以后就出现了问题，插入的日期都是获取的当天日期，这是什么情况？

**Comment by terriblegirl** [comment]
为了查看问题又用output查看数据
![image](https://user-images.githubusercontent.com/48819512/81637010-d4ae4100-9447-11ea-948f-c1545b833ff0.png)

**Comment by RickyHuo** [comment]
```
hive {
  ...
  pre_sql = "select city_name,pinyin,city_code,area_code,weather_code,to_date(start_date) as start_date from cc_dw.t_dim_city"
}
```
