### ISSUE TITLE
Flink KafkaTableStream have error,Temporary table `default_catalog`.`default_database`.`test_1` already exists

### ISSUE THREAD

**Issue by lylanchong** [InterestingLab/waterdrop#500]
**Waterdrop Version(Waterdrop版本)**
Waterdrop 2.0.0

**Flink or Spark Version(Flink 或者 Spark 版本)**
Flink

**Java or Scala Version(Java或者Scala版本)**
Java 

**Waterdrop Config(Waterdrop配置文件)**
```
env {
  execution.parallelism = 1
}

source {
  KafkaTableStream {
    consumer.zookeeper.connect = "192.168.85.197:2181"
    consumer.bootstrap.servers = "192.168.85.197:9092"
    consumer.group.id = "waterdrop5"
    topics = "metric-psmon"
    format = "json"
    schema = "{\"instance\":\"string\",\"dbName\":\"string\", \"@timestamp\":\"string\"}"
    result_table_name = "test_1"
    format.allow-comments = "true"
    format.ignore-parse-errors = "true"
  }
}

transform {
}

sink {
  ConsoleSink {}
}

```
**Error Exception**
Fatal Error, 

Please contact garygaowork@gmail.com or issue a bug in https://github.com/InterestingLab/waterdrop/issues

Reason: Temporary table `default_catalog`.`default_database`.`test_1` already exists

Exception StackTrace: org.apache.flink.table.api.ValidationException: Temporary table `default_catalog`.`default_database`.`test_1` already exists
	at org.apache.flink.table.catalog.CatalogManager.lambda$createTemporaryTable$10(CatalogManager.java:472)
	at java.util.HashMap.compute(HashMap.java:1196)
	at org.apache.flink.table.catalog.CatalogManager.createTemporaryTable(CatalogManager.java:470)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.createTemporaryView(TableEnvironmentImpl.java:282)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.createTemporaryView(TableEnvironmentImpl.java:269)

**Comment by RickyHuo** [comment]
```
env {
  execution.parallelism = 1
}

source {
  KafkaTableStream {
    consumer.bootstrap.servers = "xxx:9092"
    consumer.group.id = "waterdrop_test"
    topics = "sinabip_test"
    format = "json"
    schema = "{\"instance\":\"string\",\"dbName\":\"string\", \"@timestamp\":\"string\"}"
    result_table_name = "test_1"
  }
}

transform {
}

sink {
  ConsoleSink {}
}
```

我使用这个配置，Kafka里的数据输入为

> {"instance": "ck34", "dbName": "dbl", "@timestamp": "2020-05-20 12:00:00"}

执行是没有问题的
