### ISSUE TITLE
spark.dirver.memory 配置不生效问题

### ISSUE THREAD

**Issue by gegedebenben** [InterestingLab/waterdrop#507]
环境变量生效，但实际driver分配内存依然是默认值，望解决

**Waterdrop Version(Waterdrop版本)**

1.4.3

**Flink or Spark Version(Flink 或者 Spark 版本)**

2.4.3

**Waterdrop Config(Waterdrop配置文件)**

Please delete sensitive information(请注意删除敏感信息)

```
spark {
    spark.dirver.memory = "6g"
}

```

**Comment by garyelephant** [comment]
@RickyHuo 此用户没有按照ISSUE TEMPLATE（https://github.com/InterestingLab/waterdrop/issues/new?assignees=&labels=&template=----------issue.md&title=）提问题，你跟他聊过了是吗，知道具体什么问题？

**Comment by RickyHuo** [comment]
![image](https://user-images.githubusercontent.com/18550072/83737475-9fcb8d80-a685-11ea-8507-3451a93e8c09.png)
