### ISSUE TITLE
有异常处理吗？

### ISSUE THREAD

**Issue by zhangduo0729** [InterestingLab/waterdrop#510]
**Waterdrop Version(Waterdrop版本)**

A clear version of Waterdrop. 

**Flink or Spark Version(Flink 或者 Spark 版本)**

A clear version of Flink or Spark.

**Java or Scala Version(Java或者Scala版本)**

A clear version of Java or Scala.

**Waterdrop Config(Waterdrop配置文件)**

Please delete sensitive information(请注意删除敏感信息)

```
spark {}
input {}
filter {}
output {}
```

**Running Command(启动命令)**

请在这里添加完整的waterdrop启动命令及其参数。

**Error Exception**
Add exception about the problem here.(您可以将程序报错信息粘贴在此处)

**Screenshots**
If applicable, add screenshots to help explain your problem.（您可以将相关截图放在此处）

**Comment by RickyHuo** [comment]
请提供更多的信息或者详细描述问题以便我们能够帮到你。

**Comment by garyelephant** [comment]
@zhangduo0729 close for lacking of necessary information
