### ISSUE TITLE
[fields] is required in Version 2.0.0 ?

### ISSUE THREAD

**Issue by hxianshun** [InterestingLab/waterdrop#512]
**Waterdrop Version(Waterdrop版本)**

waterdrop-dist-2.0.0-alpha-2.11.8-release

**Flink or Spark Version(Flink 或者 Spark 版本)**

spark 2.4.3

**Java or Scala Version(Java或者Scala版本)**

java 8

**Waterdrop Config(Waterdrop配置文件)**

```
[INFO] parsed config file: {
    "env" : {
        "spark.app.name" : "Waterdrop",
        "spark.executor.instances" : 2,
        "spark.executor.cores" : 1,
        "spark.executor.memory" : "1g"
    },
    "source" : [
        {
            "pre_sql" : "select * from table_name",
            "plugin_name" : "hive",
            "table_name" : "table_name"
        }
    ],
    "transform" : [
        {
            "delimiter" : "|",
            "plugin_name" : "split"
        }
    ],
    "sink" : [
        {
            "database" : "db_name",
            "password" : "",
            "host" : "xxx.xxx.xxxx.xxx:xxx",
            "plugin_name" : "clickhouse",
            "table" : "table_name",
            "username" : "default"
        }
    ]
}
```

**Running Command(启动命令)**

/bin/start-waterdrop-spark.sh --master 'local[2]' --deploy-mode client --config ./config/application.conf

**Error Exception**
Plugin[io.github.interestinglab.waterdrop.spark.transform.Split] contains invalid config, error: please specify [fields] as a non-empty string list

[fields] is required in this version?

**Comment by RickyHuo** [comment]
Hive Input doesn't support in Waterdrop 2.x, Please try Waterdrop 1.x.

Split Transform refer to https://interestinglab.github.io/waterdrop-docs/#/zh-cn/v2/spark/configuration/transform-plugins/Split

**Comment by hxianshun** [comment]
> Hive Input doesn't support in Waterdrop 2.x, Please try Waterdrop 1.x.
> 
> Split Transform refer to https://interestinglab.github.io/waterdrop-docs/#/zh-cn/v2/spark/configuration/transform-plugins/Split

Yes, I have tried Waterdrop 1.x and succeed. Thank you.
