### ISSUE TITLE
Structured Streaming JDBD output druid connection获取问题

### ISSUE THREAD

**Issue by adg7511** [InterestingLab/waterdrop#513]
**Waterdrop Version(Waterdrop版本)**

1.4.3 
基于spark2.3.2编译的

**Flink or Spark Version(Flink 或者 Spark 版本)**

spark 2.3.2 

**Waterdrop Config(Waterdrop配置文件)**

spark {
  spark.app.name = "Waterdrop"
  spark.executor.instances = 3
  spark.executor.cores = 2
  spark.executor.memory = "1g"
}
input {
  kafkaStream {
        topics = "freight_report_test"
        consumer.bootstrap.servers = "gsc-hdpnode3.xxx.org:6667,gsc-hdpnode4.xxx.org:6667,gsc-hdpnode5.xxx.org:6667"
        consumer.group.id = "waterdrop_group9"
        result_table_name = "view_table1"
    }

}
	  
filter {}

output {
  jdbc {
        driver = "com.mysql.jdbc.Driver"
        url = "jdbc:mysql://10.88.133.141:3308/SCM"
        table = "frt_report_new"
        user = "xxx"
        password = "xxx"
        streaming_output_mode = "append"
		jdbc_output_mode="insert ignore"
    }
}

**Running Command(启动命令)**

./bin/start-waterdrop-structured-streaming.sh --master local[4] --deploy-mode client --config ./config/freight_kafka_1.conf

**Error Exception**
20/06/05 09:49:12 INFO AppInfoParser: Kafka version : 0.10.0.1
20/06/05 09:49:12 INFO AppInfoParser: Kafka commitId : a7a17cdec9eaa6c5
20/06/05 09:49:12 INFO KafkaSourceRDD: Beginning offset 37386 is the same as ending offset skipping freight_report_test 1
20/06/05 09:49:12 INFO CodeGenerator: Code generated in 148.943344 ms
20/06/05 09:49:12 INFO ClickHouseDriver: Driver registered
20/06/05 09:49:12 INFO ClickHouseDriver: Driver registered
20/06/05 09:49:15 INFO DruidDataSource: {dataSource-1} inited
20/06/05 21:48:59 WARN DruidDataSource: get connection timeout retry : 1
20/06/05 23:21:38 WARN DruidDataSource: get connection timeout retry : 1
20/06/05 23:32:53 WARN DruidDataSource: get connection timeout retry : 1

使用stdout输出数据没问题,但是使用jdbc output一直是这个状态

**Screenshots**
![图片](https://user-images.githubusercontent.com/66509832/83938877-ee566480-a80a-11ea-991a-360a9aa7992c.png)
![图片](https://user-images.githubusercontent.com/66509832/83938853-b2230400-a80a-11ea-8096-748289f70f52.png)
![图片](https://user-images.githubusercontent.com/66509832/83938863-d252c300-a80a-11ea-856d-56e19023b900.png)
上面关于druid的日志 都在这个class里

**Comment by garyelephant** [comment]
@adg7511 看起来是连不上mysql，你用mysql客户端在这台机器上能连上吗？

**Comment by adg7511** [comment]
用了另外一个jdbc output (batch用的那个)  是成功的,应该是能连上

**Comment by adg7511** [comment]
问题原因是在lib目录里放了5.1.17版本mysql driver,换成5.1.6版本就正常了
