### ISSUE TITLE
cdh flink配置问题

### ISSUE THREAD

**Issue by amy108** [InterestingLab/waterdrop#514]
**Waterdrop Version(Waterdrop版本)**

waterdrop-dist-2.0.0-alpha-2.11.8-release.zip

**Flink or Spark Version(Flink 或者 Spark 版本)**

flink1.9.0

**Java or Scala Version(Java或者Scala版本)**

java

**Waterdrop Config(Waterdrop配置文件)**

![image](https://user-images.githubusercontent.com/48902828/84015936-28606b80-a9af-11ea-816f-5335a5452fb7.png)

**Running Command(启动命令)**

./bin/start-waterdrop-flink.sh  --config ./config/application.conf

**Error Exception**
Add exception about the problem here.(您可以将程序报错信息粘贴在此处)

**Screenshots**
If applicable, add screenshots to help explain your problem.（您可以将相关截图放在此处）
![image](https://user-images.githubusercontent.com/48902828/84016010-43cb7680-a9af-11ea-8c20-8a626f602385.png)

PS：通过cdh安装的flink，配置文件单独放置的。具体该怎么写Waterdrop的配置文件waterdrop-env.sh。

**Comment by garyelephant** [comment]
@amy108 截图报错内容太少，看不到是在哪里打印的报错，排查问题需要，请再补充一下，尽可能详细，有上下文

**Comment by amy108** [comment]
> @amy108 截图报错内容太少，看不到是在哪里打印的报错，排查问题需要，请再补充一下，尽可能详细，有上下文

![image](https://user-images.githubusercontent.com/48902828/84028891-176e2500-a9c4-11ea-979a-f5d693ab05ab.png)
报错内容很简单，找不到flink配置文件。通过cdh安装的flink配置目录是/etc/flink.conf, 这个在Waterdrop里面该怎么配置

**Comment by amy108** [comment]
@garyelephant 
![image](https://user-images.githubusercontent.com/48902828/84029054-5dc38400-a9c4-11ea-8266-b477e4ef54ef.png)
报错内容很简单，找不到flink配置文件。通过cdh安装的flink的配置目录是/etc/flink/conf, 这个在Waterdrop里面该怎么配置

**Comment by garyelephant** [comment]
@amy108 可以这么做：

```
export FLINK_CONF_DIR=/etc/flink/conf
./bin/start-waterdrop-flink.sh --config ./config/application.conf
```

**Comment by garyelephant** [comment]
from tody 等待用户回复，超过3天不回复将close issue
