### ISSUE TITLE
1.5版本里面的output的clickhouse插件的host、username、database、password不支持动态参数传递

### ISSUE THREAD

**Issue by luohua09** [InterestingLab/waterdrop#528]
**1. Waterdrop Version(Waterdrop版本)**

**2. 你希望增加什么功能？请尽可能详细描述**

**3. 以上新功能的使用场景？**

**4. Additional Context Information /  其他附加信息（如有）**

**Comment by sunworthy** [comment]
1.5版本的config文件为:
{
  output{
      clickhouse{
            host="${host}"
            username="${username}"
            password="${password}"
            database="${database}"
       }
   }
}
启动命令为:
       ./waterdrop-1.5.0/bin/start-waterdrop.sh --master local[4]  --deploy-mode client --config test.conf  -i host="127.0.0.1:8123" -i username="default" -i password="111"  -i database="default"

**Comment by RickyHuo** [comment]
```
output{
  clickhouse{ 
    host=""${host}""
    username=""${username}""
    password=""${password}""
    database=""${database}""
  }
}
```

这样配置， 启动命令保持不变
