### ISSUE TITLE
config中配置spark.driver.maxResultSize=4g 任务无法识别

### ISSUE THREAD

**Issue by Shuny1206** [InterestingLab/waterdrop#534]
**Waterdrop Version(Waterdrop版本)**

1.5

**Flink or Spark Version(Flink 或者 Spark 版本)**

spark 2.4

**Java or Scala Version(Java或者Scala版本)**

java1..8.

**Waterdrop Config(Waterdrop配置文件)**

![image](https://user-images.githubusercontent.com/49746910/86528577-f7a32180-bedb-11ea-954d-8d6b4b44b95e.png)

```
spark {}
input {}
filter {}
output {}
```

**Running Command(启动命令)**

请在这里添加完整的waterdrop启动命令及其参数。
![image](https://user-images.githubusercontent.com/49746910/86528588-16a1b380-bedc-11ea-8f91-a7d63cd8f677.png)

**Error Exception**
![image](https://user-images.githubusercontent.com/49746910/86528621-63858a00-bedc-11ea-9aa1-632057b633a6.png)

**Screenshots**
If applicable, add screenshots to help explain your problem.（您可以将相关截图放在此处）

**Comment by garyelephant** [comment]
@RickyHuo 最好是维护一个配置的对应关系，而不是根据固定规则直接转换。这样确实容易出问题。
