### ISSUE TITLE
ElasticSearch和Mongodb 的增量查询和过滤

### ISSUE THREAD

**Issue by cmdares** [InterestingLab/waterdrop#537]
**1. Waterdrop Version(Waterdrop版本)**
1.X
**2. 你希望增加什么功能？请尽可能详细描述**
es 和 mongo reader 需要开启 过滤条件功能
**3. 以上新功能的使用场景？**
数据过滤，增量抽取
**4. Additional Context Information /  其他附加信息（如有）**

**Comment by RickyHuo** [comment]
关于es input过滤，可以有以下两种方式实现：
1. 通过 `filter` 部分的 `sql` 插件，es `input` 是支持 pushdown（谓词下推）的 
2. 通过 `es.query` 配置 query dsl 完成数据过滤，详情可参考 #508

**Comment by RickyHuo** [comment]
mongo input 也支持 pushdown， 可以通过 filter 部分完成过滤
