### ISSUE TITLE
 java.lang.ClassNotFoundException: org.apache.hadoop.hive.hbase.HiveHBaseTableInputFormat

### ISSUE THREAD

**Issue by zhoujuanshanghai** [InterestingLab/waterdrop#542]
[INFO] parsed config file: {
    "spark" : {
        "spark.app.name" : "Waterdrop",
        "spark.executor.instances" : 2,
        "spark.executor.cores" : 1,
        "spark.executor.memory" : "1g",
        "spark.sql.catalogImplementation" : "hive"
    },
    "input" : [
        {
            "pre_sql" : "select *  from content_center_ods.ods_policy_data_hbase limit 5",
            "plugin_name" : "hive",
            "table_name" : "policy"
        }
    ],
    "filter" : [],
    "output" : [
        {
            "plugin_name" : "stdout"
        }
    ]
}
我的batch.conf是从hive读取几条数据，但是一直不成功，报错如下截图
![image](https://user-images.githubusercontent.com/17314846/87378945-a5d85680-c5c1-11ea-89c1-3270a7fa8b68.png)

**Comment by garyelephant** [comment]
@zhoujuanshanghai 
你好，这个原因是hive input插件缺失了你需要的jar包。请从这里下载jar：https://repo1.maven.org/maven2/org/apache/hive/hive-hbase-handler/1.2.2/hive-hbase-handler-1.2.2.jar

然后把他放到plugins/hive/lib 下面，再启动waterdrop试试。

**Comment by garyelephant** [comment]
类似的ClassNotFoundExecption，可以拿找不到的class在这里搜索https://www.findjar.com/ ，就能知道它在哪个jar里面。

**Comment by garyelephant** [comment]
@zhoujuanshanghai 你好好，已经4天未看到你回复了，我们先close这个ISSUE，如果你还有问题，可以reopen
