### ISSUE TITLE
batch写入clickhouse时,clickhouse字段类型为Nullable(decimal)时会报错

### ISSUE THREAD

**Issue by adg7511** [InterestingLab/waterdrop#552]
**Waterdrop Version(Waterdrop版本)**

1.4.3

**Flink or Spark Version(Flink 或者 Spark 版本)**

2.4.3

filter中按照文档将数据转为了decimal

**Error Exception**
![image](https://user-images.githubusercontent.com/66509832/88025820-7a2c1200-cb67-11ea-9705-3deb9b509313.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/66509832/88025809-74363100-cb67-11ea-9da6-d4d6d7d620a2.png)
可能是这里没有decimal的case?

**Comment by RickyHuo** [comment]
已经在 1.5.1 修复了此问题 #549
