### ISSUE TITLE
postgresql 关键字 value 出现报错

### ISSUE THREAD

**Issue by judeshawn** [InterestingLab/waterdrop#554]
**Waterdrop Version(Waterdrop版本)**
1.4.3
A clear version of Waterdrop. 
1.4.3
**Flink or Spark Version(Flink 或者 Spark 版本)**

A clear version of Flink or Spark.

**Java or Scala Version(Java或者Scala版本)**

A clear version of Java or Scala.

**Waterdrop Config(Waterdrop配置文件)**

Please delete sensitive information(请注意删除敏感信息)

```
spark {}
input {
	#jdbc链接熟悉
	jdbc {
		driver = "org.postgresql.Driver"
		
		url = "jdbc:postgresql:///itldw?useUnicode=true&charSet=utf8&autoReconnect=true"
		
		#数据库链接用户名及密码
		user = ""
		password = ""
		
		#需要抽取的表（也可以写成查询语句，）
		 table = "(select "value" from tms.cdc_tm_ba_enum_values)d"
	
		#此插件处理后的数据，会被注册为一个可供其他插件直接访问的数据集(dataset)，或者被称为临时表(table)。此处注册的数据集(dataset)，其他插件可通过指定 source_table_name 来直接访问
		result_table_name = "cdc_tm_ba_enum_values"
		jdbc.fetchsize = 50000
	}
}
filter {
sql {
		#将其表中的字段进行转码，否则写入clickHouse时会因为字段类型不匹配而导致错误或者数据为空等现象
		 sql = "select value from cdc_tm_ba_enum_values"
   }
}
output {

#该配置为ClinkHouse配置地址
	clickhouse {
		#ClickHouse集群地址，格式为host:port，允许指定多个host。如"host1:8123,host2:8123"。
		host = ""
		
		#ClickHouse 数据库名
		database = "tms"
		
		#ClickHouse 表名
		table = "cdc_tm_ba_enum_v1"
		
		#需要输出到ClickHouse的数据字段，若不配置将会自动根据数据的Schema适配。
		 fields = ["value"]
		
		#CilckHouse数据库链接用户名及密码
		username = ""
		password = ""
		
		#每次通过ClickHouse JDBC写入数据的条数，默认为20000。
		bulk_size = 10000 
		
		#除了以上必备的 clickhouse-jdbc须指定的参数外，用户还可以指定多个非必须参数，覆盖了clickhouse-jdbc提供的所有参数，指定参数的方式是在原参数名称上加上前缀"clickhouse."
		#clickHouser连接超时时间，如果不指定这些非必须参数，它们将使用clickhouse-jdbc给出的默认值。
		clickhouse.socket_timeout = 500000
	}

}
```

**Running Command(启动命令)**

请在这里添加完整的waterdrop启动命令及其参数。
/opt/waterdrop-1.4.3/bin/start-waterdrop.sh  --master local[2] --deploy-mode client --config /opt/waterdrop-1.4.3/job/full/tms/cdc_tm_ba_enum_values1.conf

**Error Exception**
Add exception about the problem here.(您可以将程序报错信息粘贴在此处)
Exception in thread "main" java.lang.Exception: org.postgresql.util.PSQLException: ERROR: column "value" does not exist

**Screenshots**
If applicable, add screenshots to help explain your problem.（您可以将相关截图放在此处）
![image](https://user-images.githubusercontent.com/40844897/88260875-d3c34680-ccf7-11ea-88e1-e9d2fc253be7.png)

**Comment by garyelephant** [comment]
@judeshawn  tms.cdc_tm_ba_enum_values 的建表语句发一下。

**Comment by RickyHuo** [comment]
table = "(select \"value\" from tms.cdc_tm_ba_enum_values)d"
