### ISSUE TITLE
V2 split插件执行异常

### ISSUE THREAD

**Issue by angelhsf** [InterestingLab/waterdrop#555]
**Waterdrop Version(Waterdrop版本)**

 waterdrop-2.0.0

**Flink or Spark Version(Flink 或者 Spark 版本)**

 spark-2.4.2

**Java or Scala Version(Java或者Scala版本)**

java 版本1.8
scala版本scala-2.12.12

**Waterdrop Config(Waterdrop配置文件)**

Please delete sensitive information(请注意删除敏感信息)

```
env {
  spark.app.name = "Waterdrop"
  spark.executor.instances = 2
  spark.executor.cores = 1
  spark.executor.memory = "1g"
}
source {
  fakestream {
    content = ["Hello World # InterestingLab","hello chengdu # angel"]
    rate = 1
  }
}
transform {
  split {
    delimiter = ","
    fields = ["msg", "name"]
  }
}

sink {
  Console {}
}
```

**Running Command(启动命令)**

./bin/start-waterdrop-spark.sh --master 'local[2]' --deploy-mode client --config ./config/spark.batch2.conf

**Error Exception**
去掉split 运行正常，添加上split插件运行就异常

**Screenshots**
![image](https://user-images.githubusercontent.com/14212190/88497119-facc9180-cff1-11ea-8a97-63cbf1ecf524.png)

**Comment by RickyHuo** [comment]
Note that, Spark 2.x is pre-built with Scala 2.11 except version 2.4.2, which is pre-built with Scala 2.12. Spark 3.0+ is pre-built with Scala 2.12.

Please using Spark which pre-built with Scala 2.11
