### ISSUE TITLE
clickhouse集群 host配置问题

### ISSUE THREAD

**Issue by lixiaolevae** [InterestingLab/waterdrop#567]
**Waterdrop Version(Waterdrop版本)**
1.5.1
A clear version of Waterdrop. 

**Flink or Spark Version(Flink 或者 Spark 版本)**
2.4.3
A clear version of Flink or Spark.

**Java or Scala Version(Java或者Scala版本)**
1.8
A clear version of Java or Scala.

**Waterdrop Config(Waterdrop配置文件)**

Please delete sensitive information(请注意删除敏感信息)

```
spark {}
input {}
filter {}
output {
# clickhouse版本 20.7.3.20 ，clickhouse集群host配置如下
host = "172.1x.x.xxx:8123,172.1x.x.xxx:8123,172.1x.x.xxx:8123"
}
```

**Running Command(启动命令)**

请在这里添加完整的waterdrop启动命令及其参数。

**Error Exception**
Add exception about the problem here.(您可以将程序报错信息粘贴在此处)
运行时报错 java.lang.IllegalArgumentException: port is missed or wrong
**Screenshots**
If applicable, add screenshots to help explain your problem.（您可以将相关截图放在此处）

**Comment by RickyHuo** [comment]
是不是配置了 cluster 参数， 在配置cluster参数的情况下， 只需要配置一个host

**Comment by lixiaolevae** [comment]
> 是不是配置了 cluster 参数， 在配置cluster参数的情况下， 只需要配置一个host

试了下确实是这样的，谢谢。
