### ISSUE TITLE
java.lang.Byte cannot be cast to java.lang.Integer

### ISSUE THREAD

**Issue by Brucecarl** [InterestingLab/waterdrop#575]
**Waterdrop Version(Waterdrop版本)**
1.5.1
A clear version of Waterdrop. 

**Flink or Spark Version(Flink 或者 Spark 版本)**

A clear version of Flink or Spark.

**Java or Scala Version(Java或者Scala版本)**

A clear version of Java or Scala.

**Waterdrop Config(Waterdrop配置文件)**

Please delete sensitive information(请注意删除敏感信息)

```
spark {}
input {}
filter {}
output {}
```

**Running Command(启动命令)**

请在这里添加完整的waterdrop启动命令及其参数。

**Error Exception**
java.lang.Byte cannot be cast to java.lang.Integer 。
从hive同步数据到clickhouse。hive中数据类型是tinyint，clickhouse中是Uint8

**Screenshots**
If applicable, add screenshots to help explain your problem.（您可以将相关截图放在此处）

**Comment by RickyHuo** [comment]
哪行代码报错 麻烦提供清晰的异常报错

**Comment by RickyHuo** [comment]
简单的说， Spark 读取 Hive后生成的Schema类型于ClickHouse不对应， 需要将类型转换为对应的ClickHouse Jdbc 支持的类型

**Comment by hashi0** [comment]
请问您这个是怎么解决的？

**Comment by RickyHuo** [comment]
> 请问您这个是怎么解决的？

参考 https://github.com/InterestingLab/waterdrop/issues/267#issuecomment-714874892
