### ISSUE TITLE
waterdrop错误

### ISSUE THREAD

**Issue by kangyongxue** [InterestingLab/waterdrop#576]
**Waterdrop Version(Waterdrop版本)**
waterdrop-1.5.1
A clear version of Waterdrop. 

**Flink or Spark Version(Flink 或者 Spark 版本)**
2.2.3
A clear version of Flink or Spark.

**Java or Scala Version(Java或者Scala版本)**
1.8
A clear version of Java or Scala.

**Waterdrop Config(Waterdrop配置文件)**

Please delete sensitive information(请注意删除敏感信息)

spark {
  spark.sql.catalogImplementation = "hive"
  spark.app.name = "Waterdrop"
  spark.executor.instances = 2
  spark.executor.cores = 1
  spark.executor.memory = "1g"
}
input {
    hive {
        pre_sql = "select * from jxwb.dwd_securityWarning"
        table_name = "dwd_securityWarning_temp"
    }
}
filter {
    remove {
        source_field = ["year", "month"]
    }
}
output {
    clickhouse {
        host = "hadoop001:8123"
        database = "test"
        table = "dwd_securityWarning"
        fields = ["res_code", "cpunit_code", "device_code", "device_name", "device_type", "alarm_type", "alarm_value", "alarm_time","alarm_status","warning_level","alarm_end_time"]        
        username = "root"
        password = "epnTgzdG"
    }
}

**Running Command(启动命令)**

请在这里添加完整的waterdrop启动命令及其参数。
./bin/start-waterdrop.sh --config config/batch.conf -e client -m 'local[2]'
**Error Exception**
Add exception about the problem here.(您可以将程序报错信息粘贴在此处)

**Screenshots**
If applicable, add screenshots to help explain your problem.（您可以将相关截图放在此处）
![image](https://user-images.githubusercontent.com/66512184/97418878-56d1e980-1944-11eb-8fc1-c23c4aedab29.png)

**Comment by RickyHuo** [comment]
https://github.com/InterestingLab/waterdrop/issues/267#issuecomment-481063042
