### ISSUE TITLE
waterdrop可以嵌入Java/Sacla代码吗？

### ISSUE THREAD

**Issue by Trevor-zhang** [InterestingLab/waterdrop#587]
**1. Waterdrop Version(Waterdrop版本)**

**2. 你希望增加什么功能？请尽可能详细描述**
waterdrop可以嵌入Java/Sacla代码
**3. 以上新功能的使用场景？**

**4. Additional Context Information /  其他附加信息（如有）**

**Comment by Trevor-zhang** [comment]
我们希望使用waterdrop作为一个批处理工具。希望的场景是：source为hudi数据，Filter为对hudi数据的处理逻辑，无sink。

**Comment by Trevor-zhang** [comment]
`def IncrementQuery(spark: SparkSession) {
    val beginTime = "20201112195407"
    val incViewDF = spark.read.format("hudi").
      option(QUERY_TYPE_OPT_KEY, QUERY_TYPE_INCREMENTAL_OPT_VAL).
      option(BEGIN_INSTANTTIME_OPT_KEY, beginTime).
      load("oss://xxxx")
    incViewDF.show()
    incViewDF.createOrReplaceTempView("hudi_incr_table")
    val sql_ods = " select  tmp.city, count(*) as number from " +
      "(select a.cityname as city, b.partition as day from data_lake_bigdata.city_temp_new a " +
      "left join (select substring(areacode, 1, 3) as area,hivepartition as partition " +
      "from hudi_incr_table) b on a.areacode = b.area ) tmp  " +
      "GROUP BY  tmp.city limit 10"
    val df = spark.sql(sql_ods)
    df.show()
    df.createOrReplaceTempView("ods_tmp")
    val sql_dwd_update = "insert overwrite table data_lake_bigdata.order_incre_dwd partition(commit_time='" +
      beginTime + " ') select t.city,t.number from ods_tmp t"
    spark.sql(sql_dwd_update)``

**Comment by Trevor-zhang** [comment]
`def IncrementQuery(spark: SparkSession) {
    val beginTime = "20201112195407"
    val incViewDF = spark.read.format("hudi").
      option(QUERY_TYPE_OPT_KEY, QUERY_TYPE_INCREMENTAL_OPT_VAL).
      option(BEGIN_INSTANTTIME_OPT_KEY, beginTime).
      load("oss://xxxx")
    incViewDF.show()
    incViewDF.createOrReplaceTempView("hudi_incr_table")
    val sql_ods = " select  tmp.city, count(*) as number from " +
      "(select a.cityname as city, b.partition as day from data_lake_bigdata.city_temp_new a " +
      "left join (select substring(areacode, 1, 3) as area,hivepartition as partition " +
      "from hudi_incr_table) b on a.areacode = b.area ) tmp  " +
      "GROUP BY  tmp.city limit 10"
    val df = spark.sql(sql_ods)
    df.show()
    df.createOrReplaceTempView("ods_tmp")
    val sql_dwd_update = "insert overwrite table data_lake_bigdata.order_incre_dwd partition(commit_time='" +
      beginTime + " ') select t.city,t.number from ods_tmp t"
    spark.sql(sql_dwd_update)`

**Comment by Trevor-zhang** [comment]
`def IncrementQuery(spark: SparkSession) {
    val beginTime = "20201112195407"
    val incViewDF = spark.read.format("hudi").
      option(QUERY_TYPE_OPT_KEY, QUERY_TYPE_INCREMENTAL_OPT_VAL).
      option(BEGIN_INSTANTTIME_OPT_KEY, beginTime).
      load("oss://t3-data-lake-std-prod/data_lake/business/gb/ads_gb_ord_arrive_ds")
    incViewDF.show()
    incViewDF.createOrReplaceTempView("hudi_incr_table")
    val sql_ods = " select  tmp.city, count(*) as number from " +
      "(select a.cityname as city, b.partition as day from data_lake_bigdata_gb.city_temp_new a " +
      "left join (select substring(areacode, 1, 3) as area,hivepartition as partition " +
      "from hudi_incr_table) b on a.areacode = b.area ) tmp  " +
      "GROUP BY  tmp.city limit 10"
    val df = spark.sql(sql_ods)
    df.show()
    df.createOrReplaceTempView("ods_tmp")
    val sql_dwd_update = "insert overwrite table data_lake_bigdata_gb.ads_gb_order_incre_dwd partition(commit_time='" +
      beginTime + " ') select t.city,t.number from ods_tmp t"
    spark.sql(sql_dwd_update)`

**Comment by Trevor-zhang** [comment]
![image](https://user-images.githubusercontent.com/33487819/99774885-5b577f80-2b49-11eb-97bf-a789bb5cad03.png)

**Comment by Trevor-zhang** [comment]
我们期望能在waterdrop里执行IncrementQuery（）这个方法。

**Comment by Trevor-zhang** [comment]
请问这个可行吗？

**Comment by garyelephant** [comment]
@Trevor-zhang 嵌入java/scala代码指的是开发自己的业务逻辑？这个是支持的，waterdrop支持开发自己的插件，详见文档：https://interestinglab.github.io/waterdrop-docs/#/zh-cn/v1/developing-plugin
