### ISSUE TITLE
java.lang.ClassNotFoundException: io.github.interestinglab.waterdrop.flink.source.jdbc

### ISSUE THREAD

**Issue by luo438978357** [InterestingLab/waterdrop#603]
**Waterdrop Version(Waterdrop版本)**

A clear version of Waterdrop. 

**Flink or Spark Version(Flink 或者 Spark 版本)**

A clear version of Flink or Spark.

**Java or Scala Version(Java或者Scala版本)**

A clear version of Java or Scala.

**Waterdrop Config(Waterdrop配置文件)**

Please delete sensitive information(请注意删除敏感信息)

```
spark {}
input {}
filter {}
output {}
```

**Running Command(启动命令)**

请在这里添加完整的waterdrop启动命令及其参数。

**Error Exception**
Add exception about the problem here.(您可以将程序报错信息粘贴在此处)

**Screenshots**
If applicable, add screenshots to help explain your problem.（您可以将相关截图放在此处）

**Comment by garyelephant** [comment]
@luo438978357 你好，请按照提ISSUE的格式要求把Context描述完整，方便帮你查问题。

**Comment by garyelephant** [comment]
@luo438978357 close for no response for over 7+ days
