### ISSUE TITLE
插件打包，提示信息不对

### ISSUE THREAD

**Issue by lphcreat** [InterestingLab/waterdrop#606]
**Waterdrop Version(Waterdrop版本)**

1.5
**Flink or Spark Version(Flink 或者 Spark 版本)**

2.4

**Java or Scala Version(Java或者Scala版本)**

java1.8

**Waterdrop Config(Waterdrop配置文件)**
```
spark {
  spark.app.name = "ETL-1"
  spark.executor.instances = 2
  spark.executor.cores = 1
  spark.executor.memory = "1g"
  spark.sql.catalogImplementation = "hive"
  spark.hadoop.hive.exec.dynamic.partition = "true"
  spark.hadoop.hive.exec.dynamic.partition.mode = "nonstrict"
}
input {
  hive {
    pre_sql = "select * from person_loan.bs_city"
    result_table_name = "my_dataset"
  }
}
filter {
org.interestinglab.waterdrop.filter.JavaSubstring {
    source_table_name = "my_dataset"
    result_table_name = "f1"
    source_field = "city_name"
    target_field = "new_city_name"
    pos = 3
  }
  sql {
    source_table_name = "f1"
    result_table_name = "f2"
    sql = "create table feature_db_tmp.temp_city_new select * from f1"
  }
}
output {
  stdout {
    limit = 10
  }
}
```

**Running Command(启动命令)**
./bin/start-waterdrop.sh --master yarn --deploy-mode cluster --config ./config/my_test.conf
**Error Exception**
21/02/02 14:26:39 INFO Client:
         client token: N/A
         diagnostics: User class threw exception: scala.MatchError: java.util.ServiceConfigurationError: io.github.interestinglab.waterdrop.apis.BaseFilter: Provider org.interestinglab.waterdrop.filter.ScalaSubstring not found (of class java.util.ServiceConfigurationError)
        at io.github.interestinglab.waterdrop.Waterdrop$.main(Waterdrop.scala:41)
        at io.github.interestinglab.waterdrop.Waterdrop.main(Waterdrop.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$4.run(ApplicationMaster.scala:721)
**备注**
我的插件名称是org.interestinglab.waterdrop.filter.JavaSubstring，为什么提示的是 org.interestinglab.waterdrop.filter.ScalaSubstring not found？插件的路径是按照官方示例放的位置。
waterdrop-1.5.1/plugins/my_plugins/lib

**Comment by garyelephant** [comment]
你开发的是filter插件吗？
