### ISSUE TITLE
kerberos问题：spark访问kerberos认证的HDFS

### ISSUE THREAD

**Issue by huangylqf** [InterestingLab/waterdrop#627]
**Waterdrop Version(Waterdrop版本)**

1.4.3

**Spark Version(Spark 版本)**

2.4.5

**Java or Scala Version(Java或者Scala版本)**

 Java 1.8 ，Scala 2.11

spark读取具有Kerberos认证的HDFS，config怎么配置？如果添加配置不能解决，那怎么修改代码解决？

**Comment by huangylqf** [comment]
waterdrop是运行在Kubernetes上

**Comment by garyelephant** [comment]
@huangylqf 你好，请参见：https://github.com/InterestingLab/waterdrop/issues/590
