### ISSUE TITLE
waterdrop 是否支持从关系库读取配置，支持自定义个页面就能把配置配进去执行任务

### ISSUE THREAD

**Issue by QuintinTao** [InterestingLab/waterdrop#637]
**1. Waterdrop Version(Waterdrop版本)**

**2. 你希望增加什么功能？请尽可能详细描述**
是否支持从关系库读取配置，支持自定义个页面就能把配置配进去执行任务

**3. 以上新功能的使用场景？**
可以很好的集成到开发工具中

**4. Additional Context Information /  其他附加信息（如有）**

**Comment by garyelephant** [comment]
目前还不支持，短期内暂无此计划，如果你需要，可能需要自行修改waterdrop源码来实现了。

**Comment by QuintinTao** [comment]
感谢您的回答
