### ISSUE TITLE
输出到hive 报错

### ISSUE THREAD

**Issue by meihuasannong** [InterestingLab/waterdrop#644]
根据文档地址文档地址https://interestinglab.github.io/waterdrop-docs/#/zh-cn/v1/configuration/output-plugins/Hive
**Waterdrop Version(Waterdrop版本)**
v1.5.2

**Flink or Spark Version(Flink 或者 Spark 版本)**
spark

**Waterdrop Config(Waterdrop配置文件)**

```
spark {}
input {}
filter {}
output {
     Hive {
    source_table_name = "myTable2"
    result_table_name = "waterdrop.test1"
    save_mode = "overwrite"
    sink_columns = "name,age,province"
    partition_by = ["province"]
  }
}
```

**Running Command(启动命令)**

bin/start-waterdrop.sh --master spark://10.30.3.26:7077 --deploy-mode client  --config /usr/local/waterdrop/jobs/A.conf

**Error Exception**
Add exception about the problem here.(您可以将程序报错信息粘贴在此处)
Exception in thread "main" java.lang.Exception: java.lang.ClassNotFoundException: Hive
**Screenshots**
If applicable, add screenshots to help explain your problem.（您可以将相关截图放在此处）

![1628564588(1)](https://user-images.githubusercontent.com/17465324/128802122-f59b47f8-3bc9-4393-9009-af29f598377c.png)

**Comment by garyelephant** [comment]
@meihuasannong 你好，请下载刚支持hive output的v1.5.3，https://github.com/InterestingLab/waterdrop/releases/tag/v1.5.3

**Comment by meihuasannong** [comment]
> @meihuasannong 你好，请下载刚支持hive output的v1.5.3，https://github.com/InterestingLab/waterdrop/releases/tag/v1.5.3

thanks a million
