### ISSUE TITLE
JSON插件目前的问题

### ISSUE THREAD

**Issue by RickyHuo** [InterestingLab/waterdrop#73]
1. 当`target_field`为***__ROOT__***时， 由于需要从原始数据获取`schema`，导致目前没有解决办法
2. 嵌套JSON结构无法多级解析

**Comment by garyelephant** [comment]
![image](https://user-images.githubusercontent.com/2291859/32585256-345684f8-c4c2-11e7-9a90-41825ac1b6f0.png)

如果这么写，JSON Filter只能处理单层，不嵌套的json string，
{"k1":"v1", "k2":3}能处理，{"k1":"v1", "k2":{"k3":"v3"}}像这样的再嵌套一层的，就会直接报错

**Comment by RickyHuo** [comment]
目前解决方案为，先通过`spark.read.json`获取到`schema`，再根据`schema`进行转换
```
val stringDataSet = df.select(srcField).as[String]
val schema = spark.read.json(stringDataSet).schema
df.withColumn(targetField, from_json(col(srcField), schema))
```

此方案的问题是带来了额外的计算开销。

解决方案:

- 抽样而不是把所有数据转换为dataset，val stringDataSet = df.select(srcField).sample(true, 0.1).as[String]
- 如果传入的数据，本来就是JSON，就在Input之后，filter之前，一次性转换为DF：val df = spark.read.json(stringRDD)
