### ISSUE TITLE
configParse对正则表达式支持不完善

### ISSUE THREAD

**Issue by RickyHuo** [InterestingLab/waterdrop#95]
1. 使用`\s`
    > pattern = "\s"

    运行报错

2. 使用`\\s`
    > pattern = "\\s"

    configParse会对\\转义

**Comment by garyelephant** [comment]
Antlr4 escape character:

https://stackoverflow.com/questions/26894025/antlr-token-definition-for-a-string-token
https://stackoverflow.com/questions/39348288/antlr4-need-an-explanation-on-this-string-literals
https://stackoverflow.com/questions/38188274/antlr4-literal-string-handling
https://stackoverflow.com/questions/29800106/how-do-i-escape-an-escape-character-with-antlr-4
https://stackoverflow.com/questions/24557953/handling-string-literals-which-end-in-an-escaped-quote-in-antlr4
https://stackoverflow.com/questions/19236797/capturing-string-literals-with-escaped-quotes-in-antlr
https://stackoverflow.com/questions/504402/how-to-handle-escape-sequences-in-string-literals-in-antlr-3
https://github.com/antlr/antlr4/issues/1537
https://groups.google.com/forum/#!topic/antlr-discussion/eiXpuz68zsE
